### ISSUE TITLE
测试了一下demo发现了几个问题

### ISSUE THREAD

**Issue by tianshaokai** [ssseasonnn/RxDownload#1]
1. 应用下载暂停继续 会发现点击继续后 不会下载

2. 是否可以设置最大下载数量，比如下载数量 为2，其他下载的显示为等待状态

3. 更新进度条时 不是连续的，是跳跃似的更新，

**Comment by ssseasonnn** [comment]
@tianshaokai 
1. 断点续传需要服务器支持, demo中有些下载链接已经失效, 可能不支持断点续传了,所以会造成这种情况
2. 目前只支持下载, 下载管理这个功能后续会添加
3. 更新进度条是根据当前下载的进度来更新, 由于网络的原因, 下载速率不是恒定不变的, 如果一段时间内下载的数据比较多, 进度条更新就会比较多.  进度条的更新不可能每毫秒都更新一次, UI绘制的压力太大了.

最后, 谢谢你的支持

**Comment by tianshaokai** [comment]
看了网上的下载功能基本都是 连续更新的，我们最近做的下载也是 判断的下载大小和总大小，发现就没有这个问题

**Comment by tianshaokai** [comment]
还想问一下，这库是否支持下载管理呢，比如我在一个页面点击了下载后，然后进入了一个下载管理页面可以 看到正在下载的东西， .download(url, savename, savepath)， download(url, savepath) 是否增加一个这个方法呢，不传保存的名字就使用 url 最后/ 以后的字符串 作为文件名称呢

**Comment by huannan** [comment]
什么时候支持RXJava2？

**Comment by ssseasonnn** [comment]
@huannan 尽快

**Comment by ssseasonnn** [comment]
@huannan 已经支持RxJava2
