### ISSUE TITLE
大神,能否加入自由替换数据库？

### ISSUE THREAD

**Issue by Basakerone** [ssseasonnn/RxDownload#10]
RT

**Comment by ssseasonnn** [comment]
你想替换成什么?

**Comment by XiePeiXuan** [comment]
Realm

**Comment by ssseasonnn** [comment]
我看看先

**Comment by ssseasonnn** [comment]
@XiePeiXuan 你是希望只要可以用Realm代替Sqlite来存储就行了, 还是说你想自己来实现数据库的操作?

**Comment by ssseasonnn** [comment]
@XiePeiXuan 如果是前者我可以实现一套Realm的方式, 如果是后者我只能提供一个接口, 需要你自己来实现操作数据库的动作, 比较麻烦

**Comment by XiePeiXuan** [comment]
Realm代替Sqlite来存储就行了
