### ISSUE TITLE
为什么使用gradle引入框架，一直显示着等待中，并不会进行下载

### ISSUE THREAD

**Issue by HelloPeng** [ssseasonnn/RxDownload#103]
使用gradle里的架包就一直显示这样，引用下载下来的架包就没有问题，把demo里的改为gradle引用也是同样的问题。希望能够解释一下

**Comment by ssseasonnn** [comment]
检查你的代理, 确认你能正常翻墙

**Comment by HelloPeng** [comment]
不是这个意思，是运行项目，在APP中下载文件的时候。

**Comment by ssseasonnn** [comment]
已经解决了, 你再试下.

**Comment by ssseasonnn** [comment]
之前gradle的配置有点小问题.

**Comment by HelloPeng** [comment]
嗯嗯，好的。刚刚试了试ok了，刚刚以为没有说明白，想法一封邮件呢，然后邮箱里就收到了GitHub的推送通知了。谢谢啦。

**Comment by ssseasonnn** [comment]
哈哈不用客气, 😆
