### ISSUE TITLE
架包的引用包和本地的架包冲突

### ISSUE THREAD

**Issue by HelloPeng** [ssseasonnn/RxDownload#104]
架包中的v7包和我项目中的版本有冲突，需要在架包的gradle配置中修改成implementation。只需要修改v7包的配置即可

**Comment by ssseasonnn** [comment]
configurations.all {
    resolutionStrategy {
        force "com.android.support:appcompat-v7:25.4.0"
    }
}
试下在build.gradle里加上这个

**Comment by ssseasonnn** [comment]
或者
```groovy
implementation('com.android.support:appcompat-v7:25.4.0') {
        force = true
    }
```

**Comment by HelloPeng** [comment]
好像并不行，第一种方法构建完成后v7包直接没有了。第二种方法虽然我的studio是3.0的，但是用的gradle的版本是2.3.3，因为其他的一些同事并没有升级到3.0，所以implementation找不到这个方法。还有没有其他的解决方案？

**Comment by ssseasonnn** [comment]
implementation换成compile呢

**Comment by HelloPeng** [comment]
并没有效果，现在变成这样了。
![image](https://user-images.githubusercontent.com/28615755/31477378-49a69846-af3e-11e7-9d8c-613583560a7a.png)，
![image](https://user-images.githubusercontent.com/28615755/31477383-52cec218-af3e-11e7-868a-ca27b632e0e8.png)

**Comment by ssseasonnn** [comment]
```groovy
compile('zlc.season:rxdownload3:1.0.3') {
        exclude group: 'com.android.support', module: 'appcompat-v7'
}
```

**Comment by HelloPeng** [comment]
ok搞定
