### ISSUE TITLE
gradle error

### ISSUE THREAD

**Issue by DeevD** [ssseasonnn/RxDownload#105]
Error:(33, 0) Could not find method implementation() for arguments [directory 'libs'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by ssseasonnn** [comment]
Please use Android Studio 3.0

**Comment by hienhtet** [comment]
Thz u so much bro .. I got it .. Bro I have another issue that is when download start and then pause but can't start  resume.But again pause and then resume start is OK :(

**Comment by ssseasonnn** [comment]
I'm so sorry, can you update to rxdownload3 try it?

**Comment by hienhtet** [comment]
bro i found that issuse .. when add to setsavePath and setSaveName in downloadbean resume is can't  ..

**Comment by ssseasonnn** [comment]
😆 Congratulations, but it has not been maintained..

**Comment by hienhtet** [comment]
Yes bro now test rxdownload3. Can I delete downloaded url  and file bro ? Rxdownload is the best download library bro thank you. :D

**Comment by ssseasonnn** [comment]
yes you can delete the file.

**Comment by hienhtet** [comment]
👯‍♂️  Yes bro Thz

**Comment by ssseasonnn** [comment]
what error?

**Comment by hienhtet** [comment]
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

**Comment by ssseasonnn** [comment]
detail?

**Comment by hienhtet** [comment]
'tools:replace="android:authorities"' to <provider> element at AndroidManifest.xml:14:9-22:20 to override. app main manifest (this file), line 15 Error: Attribute meta-data#android.support.FILE_PROVIDER_PATHS@resource value=(@xml/__picker_provider_paths) from AndroidManifest.xml:21:17-64 is also present at AndroidManifest.xml:21:17-55 value=(@xml/provider_paths). at manifest bro

**Comment by ssseasonnn** [comment]
Did you add your own provider?

**Comment by hienhtet** [comment]
yes bro that is facebook provider :

**Comment by ssseasonnn** [comment]
Wait a minute, I'll fix it right now...

**Comment by hienhtet** [comment]
Yeachhhh bro i'm waiting really thank you :D

**Comment by ssseasonnn** [comment]
ok, update and try again.

**Comment by hienhtet** [comment]
ok bro now i will update thank you bro

**Comment by hienhtet** [comment]
that's work bro really thank you...

**Comment by ssseasonnn** [comment]
😆✌️

**Comment by ssseasonnn** [comment]
Now delete () API can delete the file directly, you can update.

**Comment by hienhtet** [comment]
wow bro i think i will ask later this fun :D thank bro ;

**Comment by hienhtet** [comment]
Bro rxdownload 3 is the best .. more powerful and easy to use  ... respect bro .. thank alot

**Comment by hienhtet** [comment]
Hi Bro can i delete all download custom mission and files? :D

**Comment by ssseasonnn** [comment]
I have just released a new version and can now delete all the missions.

**Comment by hienhtet** [comment]
ok bro :D
