### ISSUE TITLE
下载中退出程序，无法断点下载

### ISSUE THREAD

**Issue by narakai** [ssseasonnn/RxDownload#110]
下载中退出程序，无法断点下载

**Comment by narakai** [comment]
status 直接 Succeed 了

**Comment by narakai** [comment]
额，貌似你说错了，之前那个问题，Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter tag，构造函数的不能传null

**Comment by narakai** [comment]
下载问题补充下：用RxDownload.INSTANCE.create(url)这样是没问题的，可以断点，但是构造Mission来就不行了...不知道是什么原因

**Comment by ssseasonnn** [comment]
更新一下, 新加了一个构造函数, 不用传多余的rangeFlag和tag
