### ISSUE TITLE
如何删除任务和本地文件

### ISSUE THREAD

**Issue by mmengchen** [ssseasonnn/RxDownload#111]
使用  RxDownload.INSTANCE.delete(customMission).subscribe();  无法删除本地文件，再次点击下载仍然是从
断点位置继续下载

**Comment by ssseasonnn** [comment]
好的, 我把这两个功能加上.

**Comment by ssseasonnn** [comment]
更新一下, delete()现在可以删除文件了.

**Comment by mmengchen** [comment]
现在这个删除功能还是有点bug，就是这个直接调用delete()，下载进程仍然在继续，等文件下载完成了，才将本地文件删除的，这个显然是不太合理

**Comment by ssseasonnn** [comment]
先调用stop(), 再调用delete()

**Comment by mmengchen** [comment]
我想知道你修改了什么可以删除本地文件了？现在有一个问题下载成功之后是否需要手动删除任务?如果需要的话，那么本地文件也就删除了，，，需要给提供一个字段 判断是否需要删除本地文件？

**Comment by ssseasonnn** [comment]
不需要删除任务

**Comment by mmengchen** [comment]
不删除任务的话，我的任务列表中就可以没有任务了么？？

**Comment by mmengchen** [comment]
在我的任务列表中，的功能是  当下载完成时候就不进行显示已经下载的任务了，，不删除可以？？

**Comment by mmengchen** [comment]
现在调用delete()方法之后，重新下载会下载失败

**Comment by ssseasonnn** [comment]
delete() Api 增加了可选字段, 现在删除文件是可选的了.

**Comment by mmengchen** [comment]
👌
