### ISSUE TITLE
下载问题，Mission not create（我create之后紧接着就start）

### ISSUE THREAD

**Issue by SunnyQjm** [ssseasonnn/RxDownload#113]
`
d = RxDownload.INSTANCE
                .create(mission)
                .subscribe(...)
RxDownload.INSTANCE
                .start(mission)
                .subscribe()
`
然后有时候可以下载，有时候就报Mission not create

**Comment by ssseasonnn** [comment]
create是异步操作, 因此你想要create完成立即start需要把start操作放到create完成的回调里

**Comment by ssseasonnn** [comment]
文档更新了,  可以看下文档.
