### ISSUE TITLE
Custom Notification example

### ISSUE THREAD

**Issue by DeevD** [ssseasonnn/RxDownload#114]
hi bro i want to use custom notification ... please show me example bro :)

**Comment by ssseasonnn** [comment]
You can see this : https://github.com/ssseasonnn/RxDownload/blob/master/rxdownload3/src/main/java/zlc/season/rxdownload3/notification/NotificationFactoryImpl.kt

**Comment by hienhtet** [comment]
oh bro i see thank you..when  deleted mission  and then again download but mission is not create bro but when kill application and again download is create bro .. i use that function 
RxDownload.INSTANCE.delete(mission).subscribe();

**Comment by ssseasonnn** [comment]
em...Do not know how it happened..

**Comment by hienhtet** [comment]
after delete the downloaded customMission, and download that again.
the download is not show in download manager but show in notification.

**Comment by hienhtet** [comment]
after delete downloaded mission or downloadfail misson bro and agian download this same mission .. that record is not create :D not show in downloadmanagerlist .. and kill app and agian download that same mission then show in downloadmanager list bro

**Comment by ssseasonnn** [comment]
I know, that is because delete() will delete the records in the database, and this record is generated in the create() ..

**Comment by hienhtet** [comment]
please bro :D

**Comment by ssseasonnn** [comment]
call create() again after delete() can solve this problem.

**Comment by hienhtet** [comment]
omm bro can i call manual action ?

**Comment by ssseasonnn** [comment]
wait.. Do you mean that you can not download after delete()?

**Comment by ssseasonnn** [comment]
this should not happen...How do you write it?

**Comment by hienhtet** [comment]
yess bro that issue i mean ..

**Comment by ssseasonnn** [comment]
do you call stop() before delete()?

**Comment by hienhtet** [comment]
mission = new CustomMission(downloadUrl, contentId, name, picUrl1, currentDate());
        mission.setSaveName(name);
        mission.setSavePath(savePath);
        onAttach();

**Comment by hienhtet** [comment]
no bro i direct delete()

**Comment by ssseasonnn** [comment]
You should call stop() before delete()

**Comment by hienhtet** [comment]
attach() include start()

**Comment by hienhtet** [comment]
awww ok bro i try again stop() and delete()

**Comment by hienhtet** [comment]
bro its not work  i call when delete that fun->
   
 
   RxDownload.INSTANCE.stop(data.get(position)).subscribe();
   RxDownload.INSTANCE.delete(data.get(position), true).subscribe();

**Comment by hienhtet** [comment]
and download again not create in manager list but show in notification

**Comment by ssseasonnn** [comment]
Where did your manager list data come from?

**Comment by ssseasonnn** [comment]
getAllMission()?

**Comment by hienhtet** [comment]
getAllMission() bro

**Comment by ssseasonnn** [comment]
that's right, you need create() again.

**Comment by ssseasonnn** [comment]
create() will insert record into database, delete() will delete record from database, that's it.

**Comment by hienhtet** [comment]
i create again bro .. btw i check my code and test again bro thank you

**Comment by hienhtet** [comment]
bro deleted and re-download is ok ... thank you
