### ISSUE TITLE
ApkInstallExtension.Installed这个状态并不能显示

### ISSUE THREAD

**Issue by bobulucky** [ssseasonnn/RxDownload#115]
season老师，apk下载完后进行安装，安装中这个状态会有，但安装完成后status还是succeed并不是Installed。
getAllMission返回的是Misson对象而不是自定义的misson,那正在下载的文件其他的信息就获取不到了？
在做应用apk更新能提供点思路吗?
kotlin还没学习，好多看不懂，谢谢能帮我解答问题！

**Comment by ssseasonnn** [comment]
getAllMission要想获得自定义的Mission需要扩展DbActor， 你可以看一下Demo中的用法

**Comment by ssseasonnn** [comment]
安装状态好像是有点问题， 我待会看一下

**Comment by bobulucky** [comment]
那个自定义Extension只有kotlin的写法，我看javademo里没有相关的自定义Extension。
之前我用您的2版本，在状态返回有错乱问题，看到您更新3了我就一并更新了。

**Comment by ssseasonnn** [comment]
就是CustomSqliteActor, 因为getAllMission()就是从数据库里查询返回结果，所以要返回自定义的Mission就简单的扩展一下DbActor就可以了，CustomSqliteActor就是一个简单的例子

**Comment by ssseasonnn** [comment]
看下这个类：https://github.com/ssseasonnn/RxDownload/blob/master/java-demo/src/main/java/zlc/season/rxdownload/java_demo/CustomSqliteActor.java

**Comment by bobulucky** [comment]
嗯，返回自定义Misson扩展DbActor,我看到你自定义的img了

**Comment by ssseasonnn** [comment]
安装状态那个我晚点修复了再发布一下

**Comment by bobulucky** [comment]
好，我注意你的更新。那个apk更新状态我能自定义这个状态吗，有新版本打开状态变成更新状态。

**Comment by ssseasonnn** [comment]
可以，需要自定义Extension

**Comment by bobulucky** [comment]
好的，谢谢解答！1024快乐@ssseasonn,今晚早睡！

**Comment by ssseasonnn** [comment]
Installed状态已经修复了， 并且新增了一个ApkOpenExtension, 可以参考下

**Comment by bobulucky** [comment]
打开状态我这边安装完后是可以的，如果重新刷新这个状态又会变安装，不知道你那是不是有这个问题

**Comment by ssseasonnn** [comment]
修复了，再试一下

**Comment by bobulucky** [comment]
修复后状态是可以保存了。看你的更新是把状态保存在数据库了，如果数据库的数据被清除了那这个状态缺失了。在目标应用先安装好后打开我们的应用，应用列表显示目标应用还是下载状态，我觉得这种场景下不符合使用逻辑。不知道我这种想法你能同意吗

**Comment by ssseasonnn** [comment]
所以你自己应该手动去检测是否安装，而不是依赖三方库

**Comment by bobulucky** [comment]
嗯，我明白了！我看api里只有getAllMission所有任务列表，没有提供已经下载的列表吗

**Comment by ssseasonnn** [comment]
暂时没有
