### ISSUE TITLE
请教一下，您是如何保证多线程下写入安全的

### ISSUE THREAD

**Issue by houskii** [ssseasonnn/RxDownload#12]
因为我也在做一个文件下载库
[SimpleDownloader](https://github.com/houskii/SimpleDownloader)
因为SQLite并不支持并发写入，所以我在写入方法上加上synchronized，但是考虑到可能存在的效率问题，所以又把写入操作的参数放入message然后传到Handler消息队列中，结果在测试的时候发现虽然安全性保证，但写入效率更低。最后改为将文件分片，然后根据每个文件片的长度来判定断点下载的开始位置。

我学习了下您的代码，发现您没有对数据库的写入加锁也没有合并成事务而是直接操作，当任务线程增多（比如上百个）的情况下会不会有问题呢？想和您交流一下

**Comment by ssseasonnn** [comment]
因为我只在数据库中保存下载记录，不保存每个断点下载的进度，所以不需要并发写

**Comment by houskii** [comment]
那您是怎么处理断点下载进度的呢？可以指点一下位置嘛，我大概看了一下没找到...

**Comment by ssseasonnn** [comment]
@houskii 保存到文件里
