### ISSUE TITLE
下载过程中遇到问题

### ISSUE THREAD

**Issue by 547555857** [ssseasonnn/RxDownload#125]
再下载图片 或者音频的时候 ，偶尔时候 图片下载下来会是纯白色  图片再服务器上是没问题 ，包括用浏览器也测试过下载 没问题。
音频也有时候下载下来错误

**Comment by ssseasonnn** [comment]
把下载目录下的缓存删除再试下呢

**Comment by 547555857** [comment]
把那个删除了  再下载一次是好的

**Comment by 547555857** [comment]
但是  有的图片 我们根本检测不出来 是否下载的内容出错，

**Comment by ssseasonnn** [comment]
你是不是中途换了配置？比如上次是用3个线程，下载到一半又换成了4个线程这种

**Comment by 547555857** [comment]
我们测试没描述清楚，导致我们找问题很尴尬 谢谢了  再下载过程中他点击取消下载操作了 销毁了线程
