### ISSUE TITLE
学习 Rxdownlod3 遇到问题

### ISSUE THREAD

**Issue by 547555857** [ssseasonnn/RxDownload#126]
创建中
![image](https://user-images.githubusercontent.com/17868871/32648283-1f9c9754-c630-11e7-9262-2d0e07650c69.png)出现这个错
是什么原因呢？

**Comment by 547555857** [comment]
![image](https://user-images.githubusercontent.com/17868871/32648525-1ede5784-c631-11e7-8710-ebb5606054a3.png)
demo运行出现这个问题 无法正常下载

**Comment by ssseasonnn** [comment]
没遇见过，换台设备能运行吗

**Comment by 547555857** [comment]
模拟器感觉无法运行
