### ISSUE TITLE
RxDownload3 下载后的文件大小为 0 问题

### ISSUE THREAD

**Issue by Cenler** [ssseasonnn/RxDownload#128]
试了下 RxDownload3  版本,  在下载文件时, 当 content-length = -1or0时, 最终下载的文件为空文件, 大小为0, 切换回 RxDownload2 就不存在这情况

**Comment by ssseasonnn** [comment]
URL给一个

**Comment by Cenler** [comment]
连接补上, 最近比较忙
http://113.57.163.91:9090/grm/ecp/appDownLoad?version=1.1.1

**Comment by lzp-punk** [comment]
我这边是rxdownload2下载完成后发现file.length=0;在oncomplete方法中检测file的大小

**Comment by Cenler** [comment]
搞错了是因为服务器返回header中包含 transter-encoding=chunked 问题.
