### ISSUE TITLE
下载进度会超过100%

### ISSUE THREAD

**Issue by jtsky** [ssseasonnn/RxDownload#13]
我在测试过程中进行多线程多任务下载发现有些任务的下载进度会超过100%，请问一下是否是多线程导致的问题？

**Comment by ssseasonnn** [comment]
是demo中的吗

**Comment by jtsky** [comment]
不是 是我自己写的demo 是不是常规下载不支持多线程多任务下载呢

**Comment by ssseasonnn** [comment]
你是不是同一个任务开启了两次

**Comment by jtsky** [comment]
我做了同一个任务开启多次的判断 但是还是会有写任务的下载进度会超过100% 很奇怪 但是最后还想回调用onCompleted

**Comment by ssseasonnn** [comment]
你是在recyclerview里用的吗？

**Comment by jtsky** [comment]
不是 我再页面了写了3个button 点击分别开始下载三个任务  用的是同一个rxdownload实例 虽然进度超过了100%，但是最后还是会回调onCompleted，apk也是完整的

**Comment by ssseasonnn** [comment]
是chunked 下载的吧，你抓个包看看，把响应体贴出来给我看看

**Comment by jtsky** [comment]
70416788 验证信息：金台 这是我的QQ号 能加我的QQ交流下吗

**Comment by ssseasonnn** [comment]
@jtsky  270362455你加我吧

**Comment by caixingke** [comment]
看了下代码, 有一种情况是会出现下载进度超过100%的情况. 原因在于在 Continue类型的下载中, 当进行retry时, 其下载的起始点仍然是以一开始的下载点来进行, 所以出现了超出100%的情况.

**Comment by ssseasonnn** [comment]
@caixingke 看了下代码，好像的确是这样，太粗心了，谢谢指出，明天及时修复😂

**Comment by ssseasonnn** [comment]
@jtsky 新版本已经发布, 修复了下载进度可能超过100%的BUG.
