### ISSUE TITLE
may i know 

### ISSUE THREAD

**Issue by DeevD** [ssseasonnn/RxDownload#131]
hi bro i want to know clear() fun.. that fun how work just like delete()  or like clear database

 i just need to call clear() fun  after  delete mission? or clear() after delete()?

**Comment by ssseasonnn** [comment]
When you call create (),it will create  a mission and put into the MissionBox. The clear () method removes the mission from the MissionBox. Has nothing to do with the database.

**Comment by hienhtet** [comment]
Thank bro i can call after delete() api?

**Comment by ssseasonnn** [comment]
yes you can

**Comment by hienhtet** [comment]
ok bro thank :D nice library i love it
