### ISSUE TITLE
不能动态更新下载的路径

### ISSUE THREAD

**Issue by zhangwenhao2013** [ssseasonnn/RxDownload#134]
请教一个问题:我看DownloadConfig 指定了目录
 internal val DOWNLOADING_FILE_SUFFIX = ".download"
能否有办法动态指定目录,我这边的设计要求是区分文件类型,分配到指定目录去.

**Comment by zhangwenhao2013** [comment]
.setDefaultPath() 指定一个path 还是不能解决我的诉求.

**Comment by ssseasonnn** [comment]
每一个mission都可以指定路径， 你看一下Mission的构造函数

**Comment by zhangwenhao2013** [comment]
方便加QQ 聊下吗,我怕我不仅仅这么一个问题,叨扰了 1160113614

**Comment by zhangwenhao2013** [comment]
我有传递一个savepath过去 但是没生成对应的文件夹,而且下载的位置还是原路径

**Comment by zhangwenhao2013** [comment]
我有通读你的Rx教程 方便加下qq吗 rxdownlo 的使用 我有些疑惑 1160113614

**Comment by jimbray** [comment]
我也遇到同样的问题
DownloadConfig 设置了 defaultPath 
或者 单个 Mission 设置 download Path 
仍然无效
跟踪到 RealMission 里面 实际下载 mission (actual) 并不包含 我设置的 download path，而是为 空，导致最终下载到 默认Download 路径。
