### ISSUE TITLE
may i request 

### ISSUE THREAD

**Issue by DeevD** [ssseasonnn/RxDownload#136]
bro application so stuck when download file size is larger almost 300MB and above.. i feel too stuck when internet connection speed so fast bro.. My phone model is One plus 2 bro ...

**Comment by JasonXiang2014** [comment]
Hi, bro, did you ever meet memory leaks when use this library?

**Comment by hienhtet** [comment]
i think so but not sure bro .. and did you meet ??

**Comment by JasonXiang2014** [comment]
yes，I do. I have  feedback to the author, and he promises to check it out when he is free. But I have solved the leak issue use  the way of "static + weakReference" in my own project. But the scene you described, sorry, I have no idea.

**Comment by hienhtet** [comment]
Omm how is static + weakReference  bro :

**Comment by JasonXiang2014** [comment]
it means when you use handler, you will face the leak problem, make handler static and require the weakReference of Activity can avoid this problem.   If you want to reproduce the leak issue, you can try LeakCanary, it will show you the root of leak issue.  : )

**Comment by hienhtet** [comment]
thank bro which are make static for these library .your project bro? If you wish please show your sample bro thank :)

**Comment by JasonXiang2014** [comment]
It is complicated to show the sample, if you want more detail, pls leave your  contact information.

**Comment by hienhtet** [comment]
ok thank bro .. mgheinhtet1993@gmail.com

**Comment by ssseasonnn** [comment]
I found the reason for the stuck, because of allocate a large number of Objects and frequent update notification caused, I will optimize them this weekend

**Comment by hienhtet** [comment]
Thank you so much bro :D i waiting ...

**Comment by ssseasonnn** [comment]
I just released a new version 1.2.0, try it out

**Comment by hienhtet** [comment]
Wooo thank you so much bro  i will ...

**Comment by ssseasonnn** [comment]
Sorry for the wait..

**Comment by hienhtet** [comment]
ohm no..o bro .. :D i want to say thank you again for update bro ....

**Comment by hienhtet** [comment]
bro if you don't mind ...i want to learn rxJava or rxKotlin.. but i can;t found anywhere source ..please share kindly if you have book or video tutorials bro :D

**Comment by hienhtet** [comment]
hi i found new issuse when delete downloaded file and download again notification vibrate is already vibrate .. i kill app and download again is ok ... bro please check it 
this issue is not happen  version 1.1.9
i use delete for these function -->
  RxDownload.INSTANCE.stop(mission).subscribe();
            RxDownload.INSTANCE.delete(mission, true).subscribe();
            RxDownload.INSTANCE.clear(mission);

**Comment by hienhtet** [comment]
vibrate is only use in succed notification bro like this 

    private Notification succeed(NotificationCompat.Builder builder, Context context) {
        builder.setContentText("download successful");
        builder.setVibrate(new long[]{1000, 1000, 1000, 1000, 1000});
        builder.setLights(Color.GREEN, 3000, 3000);
        dismissProgress(builder);
        return builder.build();
    }
