### ISSUE TITLE
升级rxdownload3后，依赖有问题

### ISSUE THREAD

**Issue by adams-github** [ssseasonnn/RxDownload#137]
failed compile 'com.android.support:appcompat-v7:26.1.0',
我的项目是没有依赖这个包的，是这个rxdowload3框架依赖的，之前rxdownload2完全没问题；
但是我这边gradle plugin升级，其他的也升级了，这个都是报出依赖失败，我的项目最高只能依赖到compile 'com.android.support:appcompat-v7:26.0.3'

**Comment by ssseasonnn** [comment]
手动排除依赖
compile('zlc.season:rxdownload3:xxx') {
        exclude group: 'com.android.support', module: 'appcompat-v7'
}
