### ISSUE TITLE
如果下载同一个文件，每次下载的连接地址都不一样 怎么处理这个啊？

### ISSUE THREAD

**Issue by alitong** [ssseasonnn/RxDownload#143]
我看源代码保存的时候 tag  作为下载任务的key （唯一标记） 内部代码是 下载连接url是直接作为tag 使用，那么下载同一个文件，如果下载的时候 地址每次都变化 这个就出问题了，会重复下载同一个文件，这个该怎么处理？

**Comment by ssseasonnn** [comment]
你看一下Mission的构造函数

**Comment by Vander-liu** [comment]
@alitong  @ssseasonnn  还是不太懂,我这里遇到的问题是,当tag变化时,会重复向数据库插入一条新的数据.我不太清楚在哪里可以设置判断条件,过滤一下.
