### ISSUE TITLE
subscribe不回调

### ISSUE THREAD

**Issue by louisyonge** [ssseasonnn/RxDownload#144]
和例子类似，在recyclerview中的onAttach创建下载任务，这个函数执行了，点击之后，文件也下载下来了，可是consumer从来没执行，请问是什么原因呢？

····
    public void onAttach() {
        Timber.e("onAttach: " + title);
     //   UtilsKt.dispose(disposable);
        disposable = RxDownload.INSTANCE.create(zipDownloadMission)
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new Consumer<Status>() {
                    @Override
                    public void accept(Status status) throws Exception {
                        setProgress(status);
                        setActionText(status);
                        Timber.e("onAttach 1: " + status.toString());
                    }
                });
    }
····

**Comment by JasonXiang2014** [comment]
zipDownloadMission 是新建的还是查出来的？

**Comment by louisyonge** [comment]
新建的，new 出来的

**Comment by blueway** [comment]
同样的问题，第一次新建，然后开始，收不到消息，第二次进来就可以了。

**Comment by louisyonge** [comment]
@blueway 我的问题描述的可能不精确。其实意思和你说的是一样的。就是第一次从来不回调，后面的会回调。。。

**Comment by lxykad** [comment]
我遇到的问题是偶尔会不回调，大部分情况下是正常的。很难重现，没法调试
