### ISSUE TITLE
下载同一个文件删除本地文件和下载进程之后不能重新创建

### ISSUE THREAD

**Issue by mmengchen** [ssseasonnn/RxDownload#145]

**Comment by ssseasonnn** [comment]
你是指文件不能重新创建吗？我本地测试好像没问题

**Comment by mmengchen** [comment]
就是我删除任务和本地文件后，重新创建任务，进度没有更新

**Comment by q4232134** [comment]
Delete之后并没有在LocalMissionBox.SET清除RealMission，导致再创建任务的时候认为任务已存在。

**Comment by q4232134** [comment]
调用clear可以从SET中清除，但是如果开了autoStart，会导致列表界面重新开始下载，因为列表只能通过create获取RealMission的实例进行显示。

**Comment by zhangwenhao2013** [comment]
我遇到了同样的问题    导致这里会修改我的数据
   override fun start(mission: Mission): Maybe<Any> {
        var realMission = SET.find { it.actual == mission } ?:
                return Maybe.error(RuntimeException("Mission not create"))

        realMission.actual = mission
        
        return realMission.start()
    }

**Comment by zhangwenhao2013** [comment]
老铁 你最终解决问题没 
`   override fun start(mission: Mission): Maybe<Any> {
        var realMission = SET.find { it.actual == mission } ?:
                return Maybe.error(RuntimeException("Mission not create"))

        realMission.actual = mission
        
        return realMission.start()
    }`

**Comment by zhangwenhao2013** [comment]
老铁 我遇到了同样的问题  你那边最终解决没 
`   override fun start(mission: Mission): Maybe<Any> {
        var realMission = SET.find { it.actual == mission } ?:
                return Maybe.error(RuntimeException("Mission not create"))

        realMission.actual = mission
        
        return realMission.start()
    }`

**Comment by q4232134** [comment]
可以手动在delete和deleletall里面加清除，但是我的delete清除好像没有效果，你可以看看我fork的代码

**Comment by q4232134** [comment]
自动运行的问题解决了，增加了get方法

**Comment by zhangwenhao2013** [comment]
下载完成的删除  我clear 有效  ,下载中的clear 就不行了.(不是你的代码)

**Comment by q4232134** [comment]
会不会是是因为你显示的时候再次调用了create方法?

**Comment by zhangwenhao2013** [comment]
能否加个qq聊下  1160113614
