### ISSUE TITLE
RxDownload3的Extension问题

### ISSUE THREAD

**Issue by TIL-MICE** [ssseasonnn/RxDownload#146]
在java项目中添加的Extension是因为需要用java的方式去写Extension，还是说可以直接添加kotlin的Extension（这里我尝试是无法通过编译的）没怎么去了解kt在java中的混编，看文档感觉需要改比较多的地方来支持在java中的编译，是这样吗？

因为前辈的javademo中没看到添加的Extension，所以来提了这么一个 或许比较幼稚的issue

**Comment by ssseasonnn** [comment]
可以直接添加Kotlin的Extension哈

**Comment by TIL-MICE** [comment]
嗯 那可能是我使用不当 我再多试试

**Comment by TIL-MICE** [comment]
问题找到了，kotlin基础问题，顺带再问下，我看源码好像这个下载任务的唯一性还是和2一样使用的url判断的，但是我的情况是可能是同一个文件但是来自于不同的服务器，这样url就不一样，我想在保持和库同步更新，是自定义一个mission然后去使用这个构造方法吗？ DownloadMission(String url, String saveName, String savePath, Boolean rangeFlag, String tag)，自己传入tag，这样的话应该可以保证创建的时候不会重复，但是恢复时的下载链接是用的新的url还是旧的呢？（因为不熟kotlin，源码部分没太看懂，来确认下，虽然可以自己实践，但是这个作者应该是最清楚的） 谢谢啦

**Comment by TIL-MICE** [comment]
经过kotlin的部分学习后，我自己已经在项目中应用，并得到了比较好的结果，一切都正常 感谢作者

**Comment by TIL-MICE** [comment]
发现一个新的问题，我的自定义Mission使用GetAllMission拿出来的会有强转异常，creat的时候传入的是自定义Mission，因为creat方法里是父类，应该没关系才对，但是我拿出来后强转就是不行，使用instantof判断拿出来的Mission发现不是我的自定义Mission了，这里有什么要注意的吗？

**Comment by TIL-MICE** [comment]
我想我知道了，需要自己再写一个CustomSqliteActor，抱歉，应该发了很多邮件，打扰了，毕竟周末
