### ISSUE TITLE
关于多种mission构造 和多种自定义sql

### ISSUE THREAD

**Issue by yummyChina** [ssseasonnn/RxDownload#147]
3.0版本的rxdownload是不是只支持一套mission 和自定义sql啊，能同时支持多种mission构造 和多种定义sql吗

**Comment by ssseasonnn** [comment]
支持多种啊，你可以实现自己的CustomMission和自己的DbActor, 不局限于Sqlite，你可以换成你自己喜欢的数据库

**Comment by yummyChina** [comment]
不好意思多问一句：
 DownloadConfig.Builder builder = DownloadConfig.Builder.Companion.create(this)
                .enableDb(true)
                .setDbActor(new CustomSqliteActor(this))
                .enableService(true)
                .enableNotification(true)
                .addExtension(ApkInstallExtension.class)
                .addExtension(ApkOpenExtension.class);

        DownloadConfig.INSTANCE.init(builder);
看demo中是在application中初始化DbActor的，如果要使用多种，就要在不同的地方 重新调用这个api吗

**Comment by ssseasonnn** [comment]
你的意思是同时使用多种数据库？这个不支持的
