### ISSUE TITLE
很不错，求大神能加个文件上传的功能，带进度显示

### ISSUE THREAD

**Issue by momoc** [ssseasonnn/RxDownload#15]
很不错，求大神能加个文件上传的功能，带进度显示

**Comment by ssseasonnn** [comment]
上传不好做呀，因为你上传可能需要增加许多自定义的请求参数，比如token或者其他什么的，我没办法知道每个用户有什么参数呀

**Comment by momoc** [comment]
可以  就做单纯的上传   不需要token校验的
