### ISSUE TITLE
BUG提交，非多线程下载有问题，有修复建议。

### ISSUE THREAD

**Issue by q4232134** [ssseasonnn/RxDownload#157]
非多线程下载会创建文件，但是数据并没有写入导致文件大小永远为0。
之后发现是NormalTargetFile中
Okio.buffer(Okio.sink(realFile)).use { sink ->
这句代码有问题，改成
Okio.buffer(Okio.sink(shadowFile)).use { sink ->
就可以了。

**Comment by ssseasonnn** [comment]
谢谢反馈，你可以直接提个PR呀哈哈

**Comment by q4232134** [comment]
表示还真不太会用github这玩意。。。哈哈

**Comment by ssseasonnn** [comment]
给你个机会，你试一试如何（手动斜眼）

**Comment by q4232134** [comment]
是不是没办法pr指定的文件？等下别把我自己的需求也pr上来了。。。

**Comment by ssseasonnn** [comment]
你新建一个分支，然后把改动的代码放到新分支里，然后把这个新分支推送上来，建一个PR请求就可以了

**Comment by q4232134** [comment]
我的意思是我已经fork了，改动的不止这里，还有一些别的需求，但是好像没办法单独pr一个文件。还是说可以把所有改变一起提交上来，然后你来选择使用哪个？

**Comment by ssseasonnn** [comment]
好像不能吧

**Comment by q4232134** [comment]
看来我还是只能放弃这个机会了[笑哭]。
其实我还发现蛮多问题的，只是很多涉及到结构，我都不太好改~比如果status每次通知进度都是new出来的，造成资源浪费，还有之前有人提到的delete的任务SET里没有移除导致无法再次创建，强行移除的话又会和create造成的autostart产生影响。
当然还是感谢提供了这个框架让我学到了很多方面的东西。

**Comment by ssseasonnn** [comment]
已经修复了这个问题
