### ISSUE TITLE
BUG提交，小文件下载暂停回导致之后恢复直接变为完成，带解决方案。

### ISSUE THREAD

**Issue by q4232134** [ssseasonnn/RxDownload#158]
是的又是我。。。
非多线程下载暂停会直接重命名文件导致框架认为下载已经完成。
解决方案：
NormalTargetFile的
shadowFile.renameTo(realFile)
it.onComplete()
改为
if (!it.isCancelled) {
shadowFile.renameTo(realFile)
it.onComplete()
}
另外好像非多线程下载不会保存进度。

**Comment by ssseasonnn** [comment]
OK了， 因为不能断点下载，所以也没法保存进度
