### ISSUE TITLE
断点下载问题

### ISSUE THREAD

**Issue by melody1993** [ssseasonnn/RxDownload#16]
您好，大神，我想问下你这断点下载具体怎么实现的啊？我没怎么看懂，当暂停时，上次的下载进度大小在哪里记录的？然后传入到下次继续下载里

**Comment by ssseasonnn** [comment]
文件里啊

**Comment by ssseasonnn** [comment]
有一个记录文件，下载前从该文件里读取出来

**Comment by ssseasonnn** [comment]
你可以看DownloadType 这个类
