### ISSUE TITLE
Double loading the same file in the same task.

### ISSUE THREAD

**Issue by Zar86** [ssseasonnn/RxDownload#162]
Hi,ssseasonnn!
The zlc.season.rxdownload3.http.RetrofitApi.check() method  loads the entire file, only in order to know the size of the file (value header Content-Lenght). Which is not desirable for the server. You can replace GET with HEAD to get the file size.
![3](https://user-images.githubusercontent.com/25123855/36151769-a7db211e-10d9-11e8-9153-d5ec615ff0e4.jpeg)

P.s. 
I would like to be able to change the value of RANGE_DOWNLOAD_SIZE when initializing DownloadConfig.
Thanks in advance!

**Comment by ssseasonnn** [comment]
Hi，thank you for your advice.
The GET method here does not load the entire file into memory because I did not read the data from the response stream. The GET method here is because some servers do not support the HEAD method.
^_^

**Comment by Zar86** [comment]
You do not read the entire stream, but the server gives all the data to stream. I have my own server, I do not want to overload it with GET requests.

**Comment by Zar86** [comment]
I would like to be able to change the request for @HEAD when initializing DownloadConfig.

**Comment by Zar86** [comment]
Hi,ssseasonnn! How are things with our question about @Head when initializing DownloadConfig.

**Comment by ssseasonnn** [comment]
Maybe I can add an option

**Comment by ssseasonnn** [comment]
I will add this feature as soon as possible.

**Comment by Zar86** [comment]
OK. I will wait. Thank you

**Comment by ssseasonnn** [comment]
Already published.
