### ISSUE TITLE
Replace hardcode text with android resources

### ISSUE THREAD

**Issue by Zar86** [ssseasonnn/RxDownload#163]
Hi,ssseasonnn!
In class zlc.season.rxdownload3.notification.NotificationFactoryImpl, in methods:
```
suspend(builder)
waiting(builder)
downloading(builder, status)
failed(builder)
succeed(builder)
installing(builder)
installed(builder)
```
replace hard coded text with android resources, so that there is no problem with displaying the status in the notification in different languages.

Thanks in advance!

**Comment by ssseasonnn** [comment]
OH, this is the default implementation, you can customize, I can also make multi-language configuration behind, thank you for your advice
