### ISSUE TITLE
作者,有一个地方不太明白,在获取所有下载记录的方法getAllMission()这个方法存在一点疑问.

### ISSUE THREAD

**Issue by Vander-liu** [ssseasonnn/RxDownload#165]
获取所有下载记录的方法为getAllMission().

获取的对象是一个List<Mission>,这个Mission对象是不包括下载文件的状态.

假设有一类需求是根据不同的文件下载状态,展示在不同的界面.

那么我要获取下载记录时,还需要每个Mission,重新获取一遍当前下载文件的状态.

所以我的建议是在调用AllMission这个方法时 ,可不可以将文件的下载状态一并返回.

当前这也是我个人遇到问题的看法,并不是通用的需求.

**Comment by Vander-liu** [comment]
只是有点不太理解,所以想请教一下.

**Comment by Vander-liu** [comment]
我在源码上,做出些更改,在获取Mission这个过程中,我将Mission这个类添加了Status这个成员变量,但是看了你的设计,又感觉这个做又感觉有点奇怪.然后还想请教下 作者当初您将Status和Mission作区分 是为什么?
为什么这样做.

**Comment by ssseasonnn** [comment]
这个可以扩展的吧，默认的实现是没有取状态，但是你可以自己来实现具体的数据库操作，这样就可以一并返回你需要的数据了，框架里提供的数据库只是一个默认的实现
