### ISSUE TITLE
DeleteAll() is not delete bro

### ISSUE THREAD

**Issue by DeevD** [ssseasonnn/RxDownload#169]
hi bro i can't delete all using deleteAll() api bro.how can i do . i use like this 
RxDownload.INSTANCE.deleteAll(true).subscribe();

**Comment by ssseasonnn** [comment]
Did you call the create method first?

**Comment by DeevD** [comment]
deleteAll ( ) is not work .. i want delete downloaded file dir and download again ..

**Comment by fly7632785** [comment]
@DeevD if you just deleteAll with deleting file, when you refresh data, you will figure it out that the mission is existing and its status is Delete.
You can call delateAll(misison,true) and clearAll
Then the mission set will be cleared like a new one.

**Comment by DeevD** [comment]
yes bro .. I already solve this problem.BTW thank you bro
