### ISSUE TITLE
关于DownloadService的运行控制

### ISSUE THREAD

**Issue by AifeiI** [ssseasonnn/RxDownload#17]
你好，我在使用该库的时候，发现 DownloadService 启动的 DownloadMissionDispatchRunnable 线程是无法在 RxDownload 中控制的，是否可以在 RxDownload 中增加一个控制 DownloadService 的方法（检查服务状态、开启、关闭）呢？

另外，还有一个小问题，RxIoScheduler-(.*) 这些下载线程里面，会出现最后一个线程的下载速度非常慢，通常一个50MB的文件，用浏览器下载是在10秒内，但是使用RxDownload下载需要30-40秒才完成。原因就是最后启动的一个 RxIoScheduler 线程速度非常慢。

**Comment by ssseasonnn** [comment]
你不需要对这个线程进行控制, Service一旦结束这个线程自动就停止了.
另外不是启动线程的速度慢, 线程有什么启动慢不慢的问题, 是你看到它开始下载之前它需要等待请求返回, 跟你网络情况有关系.

**Comment by AifeiI** [comment]
我是指控制 DownloadService ，并非指 DownloadMissionDispatchRunnable；
“线程速度” 是我口误，我是想说“最后启动的下载线程的网络下载速度”，举个例子，下载QQ（[链接](http://dldir1.qq.com/qqfile/qq/QQ8.8/19876/QQ8.8.exe)），会生成 4 个 RxIoScheduler 线程进行多线程下载，但是最后启动的线程会有下载非常缓慢的情况，其他线程是能够快速完成下载。

**Comment by ssseasonnn** [comment]
因为每一个线程都是单独的一个HTTP请求, 所以如果这个请求很快就完成了, 网络顺畅下载就会很迅速, 如果这个请求中途遇到延迟, 那么下载就会有所延迟, 这是正常的

**Comment by AifeiI** [comment]
其它线程均完成下载后， 剩余最后一个线程也是大概以10KB/s这样速度进行下载，这个也属于正常吗？

**Comment by ssseasonnn** [comment]
这个Service是和APP运行在同一个进程里的, 不是单独的一个进程, 所以APP进程被杀掉Service就会自动退出了, 当然如果你非得要手动去关闭的话我也可以提供一个API.
你也可以直接new 一个Intent, 然后调用context.stopService(intent)去关闭这个Service.

**Comment by ssseasonnn** [comment]
是正常的, 是单独的一个HTTP请求.

**Comment by ssseasonnn** [comment]
@AifeiI 
![qq 20161227112741](https://cloud.githubusercontent.com/assets/10646230/21489679/434b56de-cc28-11e6-8ba8-cc5e07b04ce9.png)
这是我刚刚运行demo的结果,  用了十个线程去下载, 这十个线程是并行的.

**Comment by AifeiI** [comment]
因为我是分别用两种方式（一般方式、Service方式）下载同一个文件，得到两个差异比较大的下载耗时，单线程是能够在10秒完成，多线程则需要30秒。

稍后我将我的结果发上来。

**Comment by ssseasonnn** [comment]
你每一次运行的情况都会不一样, 这个跟这个请求的响应速度有关系

**Comment by AifeiI** [comment]
![logcat](https://cloud.githubusercontent.com/assets/3113485/21492488/42b3cad6-cc40-11e6-9c2b-b0da50dd3c63.png)
![cpu](https://cloud.githubusercontent.com/assets/3113485/21492489/42dc4038-cc40-11e6-9a36-bad386600855.png)

**Comment by AifeiI** [comment]
我是对同一地址试了几次，都是出现这个情况

**Comment by zhangmengxiong** [comment]
@AifeiI  https://github.com/zhangmengxiong/MXDownloadDemo
一个简单的多线程下载库  希望能帮到你~

**Comment by AifeiI** [comment]
@zhangmengxiong 谢谢，我看了你的项目，挺小巧的，我试试可否用到我的项目里面。

**Comment by ssseasonnn** [comment]
红框部分的下载速度并不慢，你自己看看左边的速度，也有300多kb好吗，最开始部分的高峰是因为把多个线程下载的速度叠加了。你下载速度最高能达到22M？

**Comment by AifeiI** [comment]
```java
public void sample(Context context) {
        File cache = context.getExternalCacheDir();
        if (cache != null && cache.exists()) {
            final String saveName = "QQ8.8.exe";
            final String savePath = cache.getPath();
            final String downloadUrl = "http://dldir1.qq.com/qqfile/qq/QQ8.8/19876/QQ8.8.exe";

            // 开始下载
            rxDownload.context(context)
                    .maxDownloadNumber(3)  //设置同时最大下载数量
                    .serviceDownload(downloadUrl, saveName, savePath)
                    .subscribe(new Action1<Object>() {
                        @Override
                        public void call(Object o) {
                            Log.d(TAG, "Start download");

                        }
                    });

            // 订阅下载状态
            downloadSub = rxDownload.receiveDownloadStatus(downloadUrl)
                    .subscribe(new Action1<DownloadEvent>() {
                        @Override
                        public void call(DownloadEvent event) {
//                            DownloadStatus status = event.getDownloadStatus();
//                            Log.d(TAG, "onProcess: progress = " + status.getPercent());

                            //当事件为Failed时, 才会有异常信息, 其余时候为null.
                            if (event.getFlag() == DownloadFlag.FAILED) {
                                Throwable throwable = event.getError();
                                Log.w(TAG, throwable);
                            } else if (event.getFlag() == DownloadFlag.COMPLETED) {
                                File file = new File(savePath, saveName);
                                if (file.exists()) {
                                    if (file.delete()) {
                                        Log.d(TAG, "完成下载，并删除下载文件");
                                        rxDownload.deleteServiceDownload(downloadUrl).subscribe();
                                    } else {
                                        Log.d(TAG, "完成下载，删除下载文件失败");
                                    }
                                } else {
                                    Log.d(TAG, "完成下载，获取下载的文件失败");
                                }
                            }
                        }
                    });
        }
    }
```

这是测试代码，**rxDownload** 没有做其他配置。

**Comment by ssseasonnn** [comment]
@AifeiI 新版本已经发布, 修复了下载进度可能超过100%的BUG,你可以看一下
