### ISSUE TITLE
notification click error

### ISSUE THREAD

**Issue by DeevD** [ssseasonnn/RxDownload#171]
bro when i add intent for notification builder .. app is too slow downloading

**Comment by ssseasonnn** [comment]
I'm testing it

**Comment by ssseasonnn** [comment]
I don't have this problem here, check the code in your NotificationFactory，or you can post it on here.

**Comment by ssseasonnn** [comment]
It looks like there is no problem... dont know why this happen...

**Comment by DeevD** [comment]
It can cause largest file bro?
I test two 300Mb download links in my app bro
