### ISSUE TITLE
Notification Request

### ISSUE THREAD

**Issue by DeevD** [ssseasonnn/RxDownload#173]
Notification is appear  for all download file in when app is first open .But download file are already pause before app are exist.bro.

**Comment by DeevD** [comment]
I expect bro. when click action button after show notification bro thank you

**Comment by DeevD** [comment]
May i request bro :)

**Comment by ssseasonnn** [comment]
This is because after the create task, it will immediately receive a state, so the NotificationFactory will create a Notification based on this state, so you can slightly modify your NotificationFactory to determine whether the first time you receive the state should be able to solve this problem

**Comment by DeevD** [comment]
bro thank you for answer . Please can you show me sample bro?

**Comment by DeevD** [comment]
This problem is not cause in version 1.1.9 bro . But 1.1.9 is ui stuck . This version is perfect bro . pendingIntent is work and no ui stuck bro :D thank. But i have above problem bro. If you don't mine please advice how to modify for my notificationFactory bro. Thank you

**Comment by DeevD** [comment]
Ok bro thank you.:D

**Comment by ssseasonnn** [comment]
public class CustomNotificationFactoryImpl implements NotificationFactory {
    private boolean isFirst = true;
    private HashMap<RealMission, NotificationCompat.Builder> map = new HashMap<>();

    @Nullable
    @Override
    public Notification build(@NotNull Context context, @NotNull RealMission mission, @NotNull Status status) {
        if (isFirst) {
            isFirst = false;
            return null;
        }

        NotificationCompat.Builder builder = get(mission, context);
        if (status instanceof Normal) {

        } else if () {

        }
    }

    private NotificationCompat.Builder get(RealMission mission, Context context) {
        NotificationCompat.Builder builder = map.get(mission);
        if (builder == null) {
            builder = createNotificationBuilder(mission, context);
            map.put(mission, builder);
        }
    }

    private NotificationCompat.Builder createNotificationBuilder(RealMission mission, Context context) {
        return new NotificationCompat.Builder(context, "")
                .setSmallIcon(R.drawable.ic_download)
                .setContentTitle("title");
    }
}

**Comment by DeevD** [comment]
yeah work perfectly bro .Save my problem Thank you so much .

**Comment by DeevD** [comment]
bro is not work when download file is one or more :(
