### ISSUE TITLE
Configure RANGE_DOWNLOAD_SIZE in DownloadConfig

### ISSUE THREAD

**Issue by BharathMG** [ssseasonnn/RxDownload#174]
Can I change RANGE_DOWNLOAD_SIZE with DownloadConfig Builder? Currently it is 4M size. I'm downloading larger file (700M). So, I would like to increase this size as per my use case. Shall I submit PR with changes making RANGE_DOWNLOAD_SIZE configurable?

**Comment by ssseasonnn** [comment]
Yes please, thank you for your contribution
