### ISSUE TITLE
在使用multiDex分包之后部分机型会提示找不到provider

### ISSUE THREAD

**Issue by jaysowen** [ssseasonnn/RxDownload#179]
在4.3系统的三星手机发布之后Didn't find class "zlc.season.rxdownload3.helper.RxDownloadFileProvider",该手机运行demo没有这个问题.怀疑是MultiDex引起的,请教如何解决?

**Comment by jaysowen** [comment]
解决了,添加multiDexKeepProguard  file('multidex-config.pro')就行了

**Comment by weitto** [comment]
具体怎么解决的啊，大兄弟
