### ISSUE TITLE
下载完后等待1.5秒的方式待商阙

### ISSUE THREAD

**Issue by caixingke** [ssseasonnn/RxDownload#18]
我看了一下代码, 这里两个地方:
一个是: 下载完后, 在流还未关完的情况下, 就进行了onComplete, 这样子有一些不妥当. 最好是在流关闭完后, 再进行onComplete; 
一个是: 因为不是在流关闭后进行onComplete, 所以在doOnCompleted中, 等待1.5s再执行其它的事后操作. 这种方式有一些被动.

**Comment by ssseasonnn** [comment]
@caixingke 😊谢谢提醒，是我没考虑周到，明天修复么么哒

**Comment by caixingke** [comment]
对了, 代码中这么处理:
`
try {
    try {
         ...
    } finally {
        Utils.close(record);
        Utils.close(recordChannel);
        Utils.close(save);
        Utils.close(saveChannel);
        Utils.close(inStream);
        Utils.close(response);
    }
} catch (IOException e) {
    Log.i(TAG, Thread.currentThread().getName() + " download failed or cancel!");
    emitter.onError(e);
}
`
比如, 在 record 流关闭失败时, 是不是会导致 save / inStream / response 等流没有进行关闭? 
所以建议流的关闭还是这样子进行:
`
try {

} catch (IOException e) {
    ...
} finally {
    try {
        Utils.close(record);
    } catch (IOException e) {

    }
    一个流一个流进行关闭
} 
`

**Comment by caixingke** [comment]
还有一个, `FileHelper.createDirectories`中的 `file.mkdir()`是否需要改为`file.mkdirs()`?

**Comment by ssseasonnn** [comment]
@caixingke 哈哈, 谢谢大神指点.

**Comment by ssseasonnn** [comment]
@caixingke 新版本已经修复了这几个问题, 谢谢大神
