### ISSUE TITLE
RxDownload: Mission error! Not Found

### ISSUE THREAD

**Issue by JiongBull** [ssseasonnn/RxDownload#181]
网上的文件删除后，创建 MISSION 就会出现这个异常，请问如何捕获?

**Comment by JiongBull** [comment]
log 能否加个开关？DEBUG 由外部传入

![_15250576531365](https://user-images.githubusercontent.com/4413502/39414142-defac01e-4c66-11e8-9707-58e177602947.png)

**Comment by ssseasonnn** [comment]
DownloadConfig里有开关

**Comment by JiongBull** [comment]
thank you.

**Comment by passself** [comment]
@JiongBull 咋解决的
