### ISSUE TITLE
开始下载后会发送多个 Succeed

### ISSUE THREAD

**Issue by changjiashuai** [ssseasonnn/RxDownload#184]
disposable = RxDownload.INSTANCE.create(mission)
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new Consumer<Status>() {
                    @Override
                    public void accept(Status status) throws Exception {
                        currentStatus = status;
                        if (currentStatus instanceof Succeed) {
                            Timber.i("onClickSaveToAlbum create: scanFile=" + saveName + ", savePath=" + savePath);
                            scanFile(savePath + "/" + saveName);
                        }
                    }
                });

**Comment by webwalker** [comment]
我也遇到了
