### ISSUE TITLE
大佬，问下如何手动更新状态

### ISSUE THREAD

**Issue by xxchenqi** [ssseasonnn/RxDownload#185]
例如，我先获取手机安装的apk，在和服务器获取的apk做比较，
如果已安装，我想更新这个状态。

**Comment by ssseasonnn** [comment]
用Extension，可以参考ApkInstallExtension

**Comment by xxchenqi** [comment]
@ssseasonnn 
大佬，我参考了ApkInstallExtension的写法，增加了一个状态 ，
但是在create的时候，状态还是Normal，不是我自定义的状态。

**Comment by ssseasonnn** [comment]
create完了以后，在回调里再调用你的Extension
