### ISSUE TITLE
下载未完成也会调用onCompleted

### ISSUE THREAD

**Issue by xgs925** [ssseasonnn/RxDownload#19]
你好，我的需求是同时下载多个文件，每下完一个文件在数据库作记录，于是我onCompleted中记录该文件已下载，结果我发现数据库中的记录与下载的文件不一致。是我哪里操作不当吗？望大神指教。

**Comment by ssseasonnn** [comment]
@xgs925 贴代码看看

**Comment by xgs925** [comment]
for (int i = 0; i < size; i++) {
                RemoteModuleList.RemoteModule remoteModule = remoteModuleList.result.get(i); 
DownloadUtil.downloadShowModule(getApplicationContext(), remoteModuleList.expressionTemplateURLHeader, remoteModule.titl, remoteModuleList.sign, new Subscriber<DownloadStatus>() {
                    @Override
                    public void onCompleted() {
                        ModuleInfo moduleInfo = new ModuleInfo();
                        moduleInfo.setTitle(remoteModuleList.result.get(finalI).titl);
                        moduleInfo.setBtid(remoteModuleList.result.get(finalI).btid);
                        moduleInfo.setSort(remoteModuleList.result.get(finalI).ortm);
                        moduleManager.addOrUpdate(moduleInfo);
                    }

                    @Override
                    public void onError(Throwable e) {
                        LogUtil.e(e.getMessage());
                    }

                    @Override
                    public void onNext(DownloadStatus downloadStatus) {
                    }
                });
}

private static RxDownload getDefaultRxDownload(Context context) {
        if (rxDownload == null)
            rxDownload = RxDownload.getInstance()
                    .maxThread(12)
                    .maxRetryCount(5)
                    .context(context);
        return rxDownload;
    }

    public static void download(Context context, String url, String saveName, String savePath, Subscriber<DownloadStatus> subscriber) {
        getDefaultRxDownload(context).download(url, saveName, savePath)
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(subscriber);
    }

**Comment by ssseasonnn** [comment]
不明白你为啥要这么封装，完全破坏了RxJava链式调用的特性，你试着不封装调用呢。
