### ISSUE TITLE
delete文件后调用startAll会把之前的文件重新下载回来

### ISSUE THREAD

**Issue by EasonHolmes** [ssseasonnn/RxDownload#190]
delete文件后调用startAll会把之前的文件重新下载回来

 override fun startAll(): Maybe<Any> {
        val arrays = mutableListOf<Maybe<Any>>()
        SET.forEach { arrays.add(it.start()) }
        return Flowable.fromIterable(arrays)
                .flatMap(INSTANCE, true)
                .lastElement()
    }
arrays的数量还包括了之前delete的数据

使用getAllMission方法获取的数据是正常的

**Comment by ssseasonnn** [comment]
clear()可以清除任务

**Comment by EasonHolmes** [comment]
但是使用clear后，之前clear的资源会无法下载，下载进度一直处于0B的状态

**Comment by laibinzhi** [comment]
但是使用clear后，之前clear的资源会无法下载，下载进度一直处于0B的状态
