### ISSUE TITLE
1.2.5 设置 Config 时报错

### ISSUE THREAD

**Issue by JiongBull** [ssseasonnn/RxDownload#196]
java.lang.NoClassDefFoundError: kotlin.jvm.internal.Intrinsics
        at zlc.season.rxdownload3.core.DownloadConfig$Builder$Companion.create(DownloadConfig.kt)

**Comment by ssseasonnn** [comment]
是不是multidex的问题

**Comment by xushanning** [comment]
同报错

**Comment by ssseasonnn** [comment]
已修复
