### ISSUE TITLE
下载的工程无法编译

### ISSUE THREAD

**Issue by Eveninger** [ssseasonnn/RxDownload#2]
![image](https://cloud.githubusercontent.com/assets/12775863/20237458/e58df96c-a90d-11e6-85cf-0de21af7f0dd.png)
开了VPN，应该不是网络的问题。报错给的下载连接在浏览器是可以下载的

**Comment by ssseasonnn** [comment]
@Eveninger 这个问题我也没遇到过，你把工程中和bintray相关的依赖删掉试试。
![img_0393](https://cloud.githubusercontent.com/assets/10646230/20238193/a492ad50-a920-11e6-8ca7-ad3ccdf81fef.PNG)
![img_0394](https://cloud.githubusercontent.com/assets/10646230/20238195/a5e4edf8-a920-11e6-9e28-488b9493200d.PNG)

**Comment by Eveninger** [comment]
感谢，已经解决问题
