### ISSUE TITLE
后台下载的时候怎么加权限？

### ISSUE THREAD

**Issue by Sabirjan** [ssseasonnn/RxDownload#20]
mRxDownload.serviceDownload(url, saveName, savePath)
                .subscribe(new Action1<Object>() {
这种下载的时候怎么加权限
//            RxPermissions.getInstance(this)
//                    .request(Manifest.permission.WRITE_EXTERNAL_STORAGE)
//                    .doOnNext(new Action1<Boolean>() {
//                        @Override
//                        public void call(Boolean granted) {
//                            if (!granted) {
//                                Toast.makeText(musicApplication, "ھوقۇقنى تەمىنلىمەپسىز", Toast.LENGTH_SHORT).show();
//                                throw new RuntimeException("no permission");
//                            }
//                        }
//                    })

这个功能怎么实现

**Comment by Sabirjan** [comment]
transformService 这个吗？
一次性加载10多个任务，卡死..怎么解决这个问题？

**Comment by ssseasonnn** [comment]
@Sabirjan transformService用法demo中有, 自行下载查看用法. 
你是怎么一次性添加的十个任务?

**Comment by Sabirjan** [comment]
就是for循环啊，我的意思是for来添加十个歌曲的下载，虽然这个东西线程里面做的，还是死机

**Comment by ssseasonnn** [comment]
你设置的最大下载任务数量是多少？线程开多了当然会卡死，你试着减少一些线程数
