### ISSUE TITLE
你好，请问有没有简单有效的方式实现POST的下载扩展呢

### ISSUE THREAD

**Issue by fly7632785** [ssseasonnn/RxDownload#202]
首先，感谢开源这个库，很不错。
其次，想问下，目前该库默认支持的是GET请求下载，如果想要用POST方式来下载，请问有没有比较简单有效的方式来进行扩展呢？查阅了一下源码，发现使用的是retrofit来实现网络下载请求的，目前除了想到fork来自己改造，请问有没有其他可行方法，求教。

**Comment by ssseasonnn** [comment]
其实也可以把这个抽象成一个接口，让你们自己去实现，不过现在没时间搞

**Comment by fly7632785** [comment]
恩 是的，我也查阅了下源码。不过的确如你所说，POST下载    少之又少。我跟后端协调一下 改成GET.

**Comment by ssseasonnn** [comment]
哈哈，就是，有问题甩锅给后端😂

**Comment by fly7632785** [comment]
😂 
看了下源码，很不错，还是学到了很多。感谢

**Comment by ssseasonnn** [comment]
写得不好，献丑了，好多bug哈哈哈😂
