### ISSUE TITLE
请问调用RxDownload.file(url)后，如果获取到file对象？rxjava不熟悉

### ISSUE THREAD

**Issue by 13588823551** [ssseasonnn/RxDownload#206]
val mission = Mission(url, saveName, savePath, true)
        disposable = RxDownload.create(mission, true)
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe { status ->
                    when (status) {
                        is Success -> {
                            Log.e(url, "isExist = ${findFile(url)?.exists()}")
                            onSuccessCallback?.invoke()
                        }
                        is Failure -> {
                            RxDownload.delete(mission, true)
                            RxDownload.clear(mission)
                            onFailureCallback?.invoke()
                        }
                        else -> onProgressCallback?.invoke(status.downloadSize, status.totalSize)
                    }
                }

fun findFile(url: String): File? {
        var file: File? = null
        RxDownload.file(url).subscribe { file = it }
        return file
    }

我的findFile方法一直返回null，是不是写法不对？

**Comment by ssseasonnn** [comment]
不能这么写大哥。。推荐你看我的RxJava教程
https://www.jianshu.com/p/464fa025229e

**Comment by 13588823551** [comment]
大佬你好，你的10篇文章我都看完了。我的问题还是无法解决，我是想得到一个file对象。
你的MissionBox.file()方法后续是否只能做流处理，无法返回file对象？

**Comment by ssseasonnn** [comment]
本来就没办法直接返回一个file对象啊，你只能返回一个Maybe<File>类型，拿到了以后在你需要file的地方进行subscribe操作，就可以在回调里拿到file了，懂否

**Comment by 13588823551** [comment]
嗯，好的。那我还是查数据库然后new个file了
