### ISSUE TITLE
自动安装在7.0存在FileUriExposedException异常

### ISSUE THREAD

**Issue by Ariescorpio** [ssseasonnn/RxDownload#21]
在7.0系统下需使用FileProvider来处理文件路径问题

**Comment by showdy** [comment]
没有适配android N吧

**Comment by ssseasonnn** [comment]
7.0你自己可以处理啊， 我已经提供了接口可以拿到下载的文件：
File file = mRxDownload.getRealFiles(saveName, defaultPath)[0];
需要你自己提供provider。

**Comment by Ariescorpio** [comment]
@ssseasonnn 恩恩，是的。下载完成后自己处理了安装

**Comment by Ariescorpio** [comment]
@showdy 恩恩，按照Android N的要求，若要在应用间共享文件，需发送一项 content://URI，并授予 URI 临时访问权限。
