### ISSUE TITLE
已下载apk,在应用列表中删除后再次下载，没有实现删除功能

### ISSUE THREAD

**Issue by liuhedev** [ssseasonnn/RxDownload#210]
如题，再次下载后，直接显示＂安装＂，进度条为０

**Comment by ssseasonnn** [comment]
删除有参数，传true是删除文件

**Comment by liuhea** [comment]
貌似是每次重新进入app，检测数据库和本地文件夹的位置有问题，还没来得及看．

**Comment by zhousongchao** [comment]
从手机目录删除文件，重新查看下载进度有问题，调用delete方法会更新但是用其他方式删除没更新
