### ISSUE TITLE
如何实现一个列表中已完成和其他状态的分组显示

### ISSUE THREAD

**Issue by zhoukai0203** [ssseasonnn/RxDownload#211]
1.列表分别显示header 下载中，下载中的文件，header 下载已完成，下载已完成的文件
2.如何能做到上面的分组呢，这个status不好取啊

**Comment by ssseasonnn** [comment]
自己写SQL查吧

**Comment by zhoukai0203** [comment]
在recyclerview中使用监听下载状态的时候存在内存泄漏的情况leakcanary检测 @ssseasonnn
