### ISSUE TITLE
May i ask

### ISSUE THREAD

**Issue by DeevD** [ssseasonnn/RxDownload#213]
Some download file is over downloading instead of actual size bro it why happen

**Comment by DeevD** [comment]
bro actually i start download like this
disposable = rxDownload.create(mission,true)
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(status -> {
                    currentStatus = status;
                }, throwable -> {

                });
and configuration information bro 
DownloadConfig.Builder builder = DownloadConfig.Builder.Companion.create(this)
                .enableDb(true)
                .setDbActor(new CustomSqliteActor(this))
                .setDefaultPath(this.getExternalCacheDir().getAbsolutePath())
                .enableNotification(true)
                .setNotificationPeriod(4L)
                .setMaxMission(1)
                .setNotificationFactory(new CustomNotifications())
                .setOkHttpClientFacotry(new CustomOkHttpClient());

        DownloadConfig.INSTANCE.init(builder);

please what i wrong bro:

**Comment by DeevD** [comment]
bro using 1.2.4 ? that issue in that version ? i need to update version bro?

**Comment by DeevD** [comment]
RxDownload: Mission error! Requested Range Not Satisfiable
 java.lang.RuntimeException: Requested Range Not Satisfiable
bro i got these error

**Comment by ssseasonnn** [comment]
Add this config  **useHeadMethod(false)** to avoid **Requested Range Not Satisfiable** error

**Comment by ssseasonnn** [comment]
Delete cache and try again.

**Comment by DeevD** [comment]
bro cache mean downloaded byte cache ?

**Comment by ssseasonnn** [comment]
Download directory and hidden files in it

**Comment by DeevD** [comment]
ok bro .. thank .  delete downloaded data and re - download again? like this bro?

**Comment by DeevD** [comment]
bro how to prevent over downloading actual size bro?

**Comment by DeevD** [comment]
Bro let me know why over downloading actual size :( 150%
