### ISSUE TITLE
over download byte ?

### ISSUE THREAD

**Issue by DeevD** [ssseasonnn/RxDownload#214]
Some download content are over downloading 100 % . How can i solve this problem bro ? thank for this library:D

**Comment by DeevD** [comment]
@ssseasonnn  bro please ..that issue happen when 5 or more download content in list bro .How to do that problem .

**Comment by ssseasonnn** [comment]
This may be caused by the viewholder reuse mechanism.

**Comment by ssseasonnn** [comment]
You should dispose original subscription before each item gets the status.

**Comment by DeevD** [comment]
😢 my pj is using recycler view bro .  any another way to solve this problem bro

**Comment by ssseasonnn** [comment]
You can see how the recycler view is implemented in the demo.

**Comment by DeevD** [comment]
bro thank you so much .. I will try.

**Comment by DeevD** [comment]
@Override
        public void onViewAttachedToWindow(ViewHolder holder) {
            super.onViewAttachedToWindow(holder);
            holder.onAttach();
        }

        @Override
        public void onViewDetachedFromWindow(ViewHolder holder) {
            super.onViewDetachedFromWindow(holder);
            holder.onDetach();
        }

@ssseasonnn  bro i already onAttach and onDetach in recycler adapter  like your sample demo but it not work bro 😢

**Comment by ssseasonnn** [comment]
```java
   class Adapter : RecyclerView.Adapter<ViewHolder>() {
        val data = mutableListOf<Mission>()

     
        override fun onCreateViewHolder(parent: ViewGroup?, viewType: Int): ViewHolder {
            val inflater = LayoutInflater.from(parent!!.context)
            return ViewHolder(inflater.inflate(R.layout.view_holder_download_item, parent, false))
        }

        override fun onBindViewHolder(holder: ViewHolder?, position: Int) {
            holder?.onBind(data[position])
        }

        override fun getItemCount(): Int {
            return data.size
        }
    }

    class ViewHolder(view: View) : RecyclerView.ViewHolder(view) {
        private var mission: Mission? = null
        private var disposable: Disposable? = null
        private var currentStatus: Status? = null

        fun onBind(mission: Mission){
            dispose(disposable)  // Dispose first !!
            disposable = RxDownload.create(mission.url)
                    .observeOn(mainThread())
                    .subscribe {
                        currentStatus = it
                        setProgress(it)
                        setActionText(it)
                    }
        }  
   } 
```

**Comment by ssseasonnn** [comment]
@DeevD try this,  dispose first then subscribe

**Comment by DeevD** [comment]
ok bro i will try .. Thank for suggestion bro 👍

**Comment by DeevD** [comment]
bro i got these error from server 
    java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)

it can be fault of server side ?

**Comment by DeevD** [comment]
@ssseasonnn    dispose(disposable)  // Dispose first !! is not for over downloading.. :*(
