### ISSUE TITLE
错误: 程序包zlc.season.rxdownload.java_demo.databinding不存在 import zlc.season.rxdownload.java_demo.databinding.ActivityAppListBinding

### ISSUE THREAD

**Issue by mjsheng** [ssseasonnn/RxDownload#215]
classpath 'com.android.tools.build:gradle:3.0.1'

distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip

**Comment by mjsheng** [comment]
ok 谢谢 java的不可用了吗

**Comment by ssseasonnn** [comment]
可以用啊，只是Java demo中的databinding可能有点问题

**Comment by mjsheng** [comment]
嗯嗯 谢谢回复
