### ISSUE TITLE
Detect Log 

### ISSUE THREAD

**Issue by DeevD** [ssseasonnn/RxDownload#216]
RxDownload: Mission error! Not Found get message from download manager bro. But i cannot get error message from throwable from my adapter 

 viewHolderDisposable = RxDownload.INSTANCE.create(customMission, false)
                    .observeOn(AndroidSchedulers.mainThread())
                    .subscribe(status -> {
                        currentStatus = status;
                        setActionText(status);
                        setProgress(status);

                    }, throwable ->
                    {
                        Log.i(TAG, " download error form mission " + throwable.getMessage());
                        Log.i(TAG, " download error form mission " + throwable.getCause());
                    });
never catch throwable bro

**Comment by ssseasonnn** [comment]
Error message in failure state.
class Failed(status: Status, val throwable: Throwable) : Status(status)

**Comment by DeevD** [comment]
Thank bro.
