### ISSUE TITLE
Download doesn't start

### ISSUE THREAD

**Issue by plentz** [ssseasonnn/RxDownload#217]
Hi! I'm trying to use RxDownload, but the download never starts (or at least doesn't show in the status bar) and doesn't start - I receive only one status with `0,0%`. I'm using the default configs. What I'm doing wrong?

```java
rxDownload.create(mission, true)
  .subscribe(new DefaultResourceSubscriber<Status>() {
      @Override
      public void onError(Throwable e) {
          Logger.w("Problems during download", e);
      }

      @Override
      public void onNext(Status status) {
          Logger.d("Got notified about file", status.percent());
          request(1);
      }
  });
```

**Comment by DeevD** [comment]
You should need to start with RxDownload.start(mission).subscribe() fun bro

**Comment by ssseasonnn** [comment]
Have you request for storage permission?

**Comment by plentz** [comment]
yes. btw, in the readme you mention 
```
<uses-permission android:name="android.permission.MOUNT_UNMOUNT_FILESYSTEMS"/>
```

which android studio gives me the alert: `Permissions with the protection level signature, privileged or signatureOrSystem are only granted to system apps. If an app is a regular non-system app, it will never be able to use these permissions`
