### ISSUE TITLE
删除下载任务，数据库并没有删除干净

### ISSUE THREAD

**Issue by rysq008** [ssseasonnn/RxDownload#218]
有一个很明显的bug就是删除下载任务包括文件以后，数据库里面的数据并没有删除掉，当你点全部开始下载以后，你删除的任务又开始下载了而且进度值还在。

**Comment by DeevD** [comment]
you should use   RxDownload.clearAll().subscribe()
 method after  RxDownload.deleteAll(true).subscribe()
mission bro

**Comment by fly7632785** [comment]
```
 RxDownload.INSTANCE.delete(false).subscribe();
 RxDownload.INSTANCE.clear().subscribe();
```
应该改为：
```
  RxDownload.INSTANCE.delete(false).subscribe(o -> {
          RxDownload.INSTANCE.clear().subscribe();
                                    });
```

原因我这边大致说下，由于两者方法里面都有对其SET(mission容器的操作)，如果不是串行使用的话，可能出现 clear已经从SET中移除掉了mission，然后delete的时候发现SET中已经没有了mission，就会停止后续代码执行，并且报mission not create错误。



总之就是 clear这种最好放在前面delete的subscribe回调里面执行，保证其执行顺序

**Comment by rysq008** [comment]
哦，我发现这个问题了。只不过用别的方式解决的，不过当然没你的这种方式解决好




    
    
        
            
                
                    
                        
                    
                    
                        
                            李亚斌
                            
                            
                                
                                    邮箱：rysq008@gmail.com
                                
                        
                    
                
            
        
    
签名由 网易邮箱大师 定制


在2018年11月26日 17:34，Jafir 写道：  RxDownload.INSTANCE.delete(false).subscribe();
 RxDownload.INSTANCE.clear().subscribe();

应该改为：
  RxDownload.INSTANCE.delete(false).subscribe(o -> {
          RxDownload.INSTANCE.clear().subscribe();
                                    });

原因我这边大致说下，由于两者方法里面都有对其SET(mission容器的操作)，如果不是串行使用的话，可能出现 clear已经从SET中移除掉了mission，然后delete的时候发现SET中已经没有了mission，就会停止后续代码执行，并且报mission not create错误。
总之就是 clear这种最好放在前面delete的subscribe回调里面执行，保证其执行顺序

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ssseasonnn/RxDownload","title":"ssseasonnn/RxDownload","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/ssseasonnn/RxDownload"}},"updates":{"snippets":[{"icon":"PERSON","message":"@fly7632785 in #218: ```\r\n RxDownload.INSTANCE.delete(false).subscribe();\r\n RxDownload.INSTANCE.clear().subscribe();\r\n```\r\n应该改为：\r\n```\r\n  RxDownload.INSTANCE.delete(false).subscribe(o -\u003e {\r\n          RxDownload.INSTANCE.clear().subscribe();\r\n                                    });\r\n```\r\n\r\n原因我这边大致说下，由于两者方法里面都有对其SET(mission容器的操作)，如果不是串行使用的话，可能出现 clear已经从SET中移除掉了mission，然后delete的时候发现SET中已经没有了mission，就会停止后续代码执行，并且报mission not create错误。\r\n\r\n\r\n\r\n总之就是 clear这种最好放在前面delete的subscribe回调里面执行，保证其执行顺序"}],"action":{"name":"View Issue","url":"https://github.com/ssseasonnn/RxDownload/issues/218#issuecomment-441574389"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ssseasonnn/RxDownload/issues/218#issuecomment-441574389",
"url": "https://github.com/ssseasonnn/RxDownload/issues/218#issuecomment-441574389",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [ssseasonnn/RxDownload] 删除下载任务，数据库并没有删除干净 (#218)",
"sections": [
{
"text": "",
"activityTitle": "**Jafir**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@fly7632785",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"ssseasonnn/RxDownload\",\n\"issueId\": 218,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"ssseasonnn/RxDownload\",\n\"issueId\": 218\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/ssseasonnn/RxDownload/issues/218#issuecomment-441574389"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 358260369\n}"
}
],
"themeColor": "26292E"
}
]
