### ISSUE TITLE
看了这么多评论，难道就没有人碰到内存泄漏？

### ISSUE THREAD

**Issue by weitto** [ssseasonnn/RxDownload#224]
使用leakcanary检测，报出RxThreadFactory$RxCustomThread 线程泄漏

**Comment by weimingyu9312** [comment]
内存泄漏解决了吗，我下载了一个超过150m的文件就会内存泄漏：D/dalvikvm: GC_FOR_ALLOC freed 1849K, 86% free 18509K/125352K, paused 53ms, total 54ms
