### ISSUE TITLE
如何在下载文件前获取文件是否下载过和下载是否完成的状态？还有能否加入同时查询多个url的状态和值？以及能否加入没有文件名称自动获取服务器的文件名？

### ISSUE THREAD

**Issue by yuanxingxing** [ssseasonnn/RxDownload#23]
使用getDownloadRecord方法如果没有下载过，数据库没有记录onnext方法不会调用。
 public Observable<DownloadRecord> readRecord(final String url) {
        return Observable.create(new Observable.OnSubscribe<DownloadRecord>() {
            @Override
            public void call(Subscriber<? super DownloadRecord> subscriber) {
                Cursor cursor = null;
                try {
                    cursor = getReadableDatabase().rawQuery("select * from " + TABLE_NAME +
                            " where " + "url=?", new String[]{url});
                    while (cursor.moveToNext()) {
                        subscriber.onNext(Db.RecordTable.read(cursor));
                    }
                    subscriber.onCompleted();
                } finally {
                    if (cursor != null) {
                        cursor.close();
                    }
                }
            }
        }).subscribeOn(Schedulers.io()).observeOn(AndroidSchedulers.mainThread());
    }
cursor.moveToNext()为false的时候没有onnext的调用只有onCompleted
获取不到文件的状态。

**Comment by ssseasonnn** [comment]
用receiveDownloadStatus()，不管是否下载， 都能收到状态。

**Comment by ssseasonnn** [comment]
现在还没有批量添加下载任务和查询多个下载状态的方法， 后续会逐渐完善和增加。
最近工作比较忙，更新比较慢， 请谅解。

**Comment by ssseasonnn** [comment]
自动获取服务器的文件名之前考虑过， 根据响应头的ContentDisposition字段来获取文件名， 但是这样会多增加一次网络请求，权衡了一下觉得并不值得这么做。

**Comment by caixingke** [comment]
判断文件名的操作, 上层自己处理就可以(如果不指定文件名, 则查询`ContentDisposition`; 如果ContentDisposition也没查到, 则使用url; 如果url不便做为文件名, 则采用其对应的md5, 等等). 
我在我司的项目中, 其实也涉及到这个问题. 因为项目工期的问题, 我只是简单的做如上所述的判断. 
当时是有过如下的考虑的:
(1)如果有指定文件名, 则直接将url和文件名保存到`mDownloadRecord`; 如果没有指定文件名, 则只将url保存到`mDownloadRecord`中.
(2)然后发起一个查询请求(查询是否支持range/是否有指定文件名等). 如果没有指定文件名的话, 则从`ContentDisposition`来读取文件名等得到一个文件名的操作, 然后填入`mDownloadRecord`集合中 . 后面再来进行对下载文件是否已存在/是否支持range等的判断之类的操作. 
这样做的话, 就不需要再额外增加一个网络请求.

**Comment by ssseasonnn** [comment]
@caixingke 恩，等忙完这段时间，好好重新思考一下。

**Comment by yuanxingxing** [comment]
3q

**Comment by ssseasonnn** [comment]
新版本修复了这几个问题，具体请看文档及代码🙂
