### ISSUE TITLE
下载完成删除不掉

### ISSUE THREAD

**Issue by XiongKe94** [ssseasonnn/RxDownload#238]

**Comment by jeff-sun** [comment]
我也遇到同样的问题了,而且这个任务还在

**Comment by XiongKe94** [comment]
> 我也遇到同样的问题了,而且这个任务还在

我准备换架构了 打算这个没人维护

**Comment by jeff-sun** [comment]
> > 我也遇到同样的问题了,而且这个任务还在
> 
> 我准备换架构了 打算这个没人维护

你换成哪个了?

**Comment by XiongKe94** [comment]
> > > 我也遇到同样的问题了,而且这个任务还在
> > 
> > 
> > 我准备换架构了 打算这个没人维护
> 
> 你换成哪个了?

okdownload 这个

**Comment by fly7632785** [comment]
这里提供一个可能出现的问题的解决方法：
导致删不掉的代码：
```
 RxDownload.INSTANCE.deleteAll(false).subscribe();
 RxDownload.INSTANCE.clearAll().subscribe();
```
应该改为：
```
  RxDownload.INSTANCE.deleteAll(false).subscribe(o -> {
          RxDownload.INSTANCE.clearAll().subscribe();
                                    });
```

原因我这边大致说下，由于两者方法里面都有对其SET(mission容器的操作)，如果不是串行使用的话，可能出现 clear已经从SET中移除掉了mission，然后delete的时候发现SET中已经没有了mission，就会停止后续代码执行，并且报mission not create错误。

**Comment by XiongKe94** [comment]
> 这里提供一个可能出现的问题的解决方法：
> 导致删不掉的代码：
> 
> ```
>  RxDownload.INSTANCE.delete(false).subscribe();
>  RxDownload.INSTANCE.clear().subscribe();
> ```
> 应该改为：
> 
> ```
>   RxDownload.INSTANCE.delete(false).subscribe(o -> {
>           RxDownload.INSTANCE.clear().subscribe();
>                                     });
> ```
> 原因我这边大致说下，由于两者方法里面都有对其SET(mission容器的操作)，如果不是串行使用的话，可能出现 clear已经从SET中移除掉了mission，然后delete的时候发现SET中已经没有了mission，就会停止后续代码执行，并且报mission not create错误。

暂时不用了 不用这个库了 优化也做的不好😂
