### ISSUE TITLE
关于 DataBaseHelper 的 readRecord 实现

### ISSUE THREAD

**Issue by AifeiI** [ssseasonnn/RxDownload#24]
我认为 DataBaseHelper 类中 readRecord 方法的实现不是很好。

**现有方式**：

当数据库找不到相应数据，是直接调用 subscriber.onCompleted()，没有调用 subscriber.onNext() 方法。

**会出现的问题**：

当对 RxDownload.getDownloadRecord() 返回的 Observable 对象使用 subscribe(new Action1<DownloadRecord>() {...}) 方法订阅时，会无法触发 call() ，这样没办法很好地结合其它 Observable 做链式处理（map、concatMap指令等等）

**想法**：

在 readRecord 方法中，增加 subscriber.onNext() 的调用，例如：

```java
cursor = getReadableDatabase().rawQuery("select * from " + TABLE_NAME + " where " + "url=?", new String[]{url});
if (cursor.moveToNext()) {
    subscriber.onNext(Db.RecordTable.read(cursor));
    while (cursor.moveToNext()) {
        subscriber.onNext(Db.RecordTable.read(cursor));
    }
} else {
    subscriber.onNext(null);
}
subscriber.onCompleted();
```

**Comment by ssseasonnn** [comment]
不是问题。

**Comment by AifeiI** [comment]
不是问题？怎么结合其他 Observable 使用？

**Comment by ssseasonnn** [comment]
该怎么结合怎么结合，本身当发射0个数据时所有的操作符都不会有效果，不知道你是怎么理解RxJava的

**Comment by AifeiI** [comment]
just   -> findRecord()
filter -> ifExist()
map -> download()
map -> returnFile()

findRecord() 就是调用 RxDownload.getDownloadRecord()，没有记录的话，下面所有的操作都不会进行

**Comment by ssseasonnn** [comment]
没有记录执行后面的filter+map没有必要了啊已经。

**Comment by AifeiI** [comment]
下载业务的流程
1、查找下载记录
2、是否已下载完成，且文件存在（不是所有的服务器都能提供断点下载）
3、已存在则直接返回文件路径，不存在则进行下载
4、解析文件路径返回文件对象

**Comment by ssseasonnn** [comment]
当返回的数据大于0时，执行filter+map没问题，返回0个数据你还去过滤什么呢

**Comment by AifeiI** [comment]
我是看RxDownload有下载记录，所以就希望结合查询记录去处理是否进行下载

**Comment by ssseasonnn** [comment]
我明白你的意思了，你是说你想当这条记录不存在的时候去执行其他的操作对吧

**Comment by AifeiI** [comment]
是的

**Comment by AifeiI** [comment]
直接加 doOnCompleted 只能驱动下面的操作继续进行，无法真实判断是否已下载了

**Comment by ssseasonnn** [comment]
新版本中修改了，请查看文档。
