### ISSUE TITLE
多文件下载

### ISSUE THREAD

**Issue by cc2hh** [ssseasonnn/RxDownload#248]
我有多个文件需要下载，能同时下载几个（例如：3个），在文件都下载完时，我得到一个反馈，再进行下一步操作。
现在我是这样做的
 List<Mission> missions = new ArrayList<>();
RxDownload.INSTANCE.createAll(missions, true).subscribe(item -> {});
这个item是Object，我没有下载状态。不知道什么时候所有文件都下载完成了。
像我这种需求应该怎么使用？是创建多个RxDownload.INSTANCE.create()，来监听每个下载状态，还是怎么使用呢？

**Comment by ZuccCircle** [comment]
使用rxjava的zip操作符观察多个数据源(RxDownload.INSTANCE.create),  应该能解决你的问题

**Comment by chrissen0814** [comment]
请问已经解决了吗
