### ISSUE TITLE
Why is MOUNT_UNMOUNT_FILESYSTEMS permission required?

### ISSUE THREAD

**Issue by qandeelabbassi** [ssseasonnn/RxDownload#253]
Can we skip the MOUNT_UNMOUNT_FILESYSTEMS permission safely?

**Comment by ssseasonnn** [comment]
yes you can

**Comment by qandeelabbassi** [comment]
Can you explain why is it there? What's its use case?

**Comment by ssseasonnn** [comment]
It was just a mistake...

**Comment by ssseasonnn** [comment]
I will fix it right away.
