### ISSUE TITLE
为什么是kotin写法，有没有纯Java写法

### ISSUE THREAD

**Issue by ruanguihua** [ssseasonnn/RxDownload#254]

**Comment by ssseasonnn** [comment]
有java demo

**Comment by ruanguihua** [comment]
依赖的 medule就是kotin

**Comment by LuckyJayce** [comment]
@ruanguihua android studio menu -> tool -> kotlin -> showKotlinByte -> decomplie 可以看到反编译后的java代码

**Comment by LuckyJayce** [comment]
不过建议还是学下kotlin
