### ISSUE TITLE
提个需求，支持自定义 Http header

### ISSUE THREAD

**Issue by gavinliu** [ssseasonnn/RxDownload#264]
有些系统的权限控制是放在 header 里面的，现在还不支持自定义

**Comment by ssseasonnn** [comment]
支持的,setOkHttpClientFacotry

Liu Yunlong <notifications@github.com> 于2019年5月5日周日 下午5:12写道：

**Comment by gavinliu** [comment]
虽然可以通过自定义 HttpClient 实现，但是感觉还是在 mission 里面加个 header 字段，要方便些
