### ISSUE TITLE
okhttp4下无法下载

### ISSUE THREAD

**Issue by zhousongchao** [ssseasonnn/RxDownload#271]
okhttp:4.0.0-alpha02下新建下载任务报错，但是已经开始的任务可以继续：
D/OpenGLRenderer: Swap behavior 1
D/NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: true
切换回okhttp3正常
希望后面更新能在okhttp4使用

**Comment by ssseasonnn** [comment]
这个是缺少Android P的network security config配置, 网上搜索一下添加上就行了
