### ISSUE TITLE
RxDownload:1.0.1调用taskManager.delete()无效

### ISSUE THREAD

**Issue by vihuela** [ssseasonnn/RxDownload#278]
删除，发现内部文件删除删除用deleteOnExit无效，改成delete()即可
![image](https://user-images.githubusercontent.com/6533060/64344782-b921a980-d021-11e9-9bcd-7f8a3b1711f5.png)

**Comment by ssseasonnn** [comment]
恩这个bug已经修复了,  还没发布, 下个版本就带上
