### ISSUE TITLE
老哥，这里有个RxCachedThreadS的问题

### ISSUE THREAD

**Issue by vihuela** [ssseasonnn/RxDownload#279]
开始下载，删除->开始下载，重复，大概率触发这个崩溃，看网上说okhttp异常，是否有解决方案呀？？
log：机型xiao'mi小米5A
Fatal signal 7 (SIGBUS), code 2, fault addr 0x7f60df4000 in tid 1399 (RxCachedThreadS)
![image](https://user-images.githubusercontent.com/6533060/64399755-4275c200-d09c-11e9-9e50-a650259b855d.png)

**Comment by ssseasonnn** [comment]
我也发现了, 正在测试修复中

**Comment by vihuela** [comment]
谢谢老哥，希望快速定位。。我们打算用到商业项目里。。

**Comment by ssseasonnn** [comment]
ojbk

**Comment by zhuangzhitu** [comment]
![image](https://user-images.githubusercontent.com/13757638/64402708-69d28c00-d0a8-11e9-9148-bd89d713ddc8.png)
一样的问题。。。不过我用的是rx download 3

**Comment by ssseasonnn** [comment]
@vihuela 1.0.2 发布了, 看看还有这个问题没

**Comment by vihuela** [comment]
@ssseasonnn 老哥高效率，谢谢，周一到公司我试下

**Comment by vihuela** [comment]
@ssseasonnn 经过测试，仍然存在这个问题，但触发概率小了些，这个问题的原因是什么呢？

**Comment by ssseasonnn** [comment]
你触发的必现路径是什么?

**Comment by ssseasonnn** [comment]
可否把你的代码发一份给我

**Comment by vihuela** [comment]
@ssseasonnn 老哥你加我微信，v13145，给你demo，可以定位的话，你这个库是极好的。

**Comment by vihuela** [comment]
暂时没有这个问题了，优秀
