### ISSUE TITLE
无网络问题时下载问题

### ISSUE THREAD

**Issue by ghoulhyk** [ssseasonnn/RxDownload#280]
使用taskManager.subscribe监听下载状态，taskManager.start()开始下载时没有连接网络，不会回调Failed状态

**Comment by ssseasonnn** [comment]
稍等我试试

**Comment by ssseasonnn** [comment]
会回调啊, 你看一下日志呢,  有状态回调的日志

**Comment by ghoulhyk** [comment]
请问在第一次的错误回调中可以调用taskManager.start()再次开启下载吗？我刚试了几次，第一次的回调一般都有，但是再次下载就没有了

**Comment by ssseasonnn** [comment]
可以啊

**Comment by ssseasonnn** [comment]
建议跑一下demo看下
