### ISSUE TITLE
每次重启app，怎么查询某文件下载状态

### ISSUE THREAD

**Issue by bossAnmi** [ssseasonnn/RxDownload#284]
难道都要启动新任务才行

**Comment by ssseasonnn** [comment]
获取单个任务的状态是吧?

**Comment by ssseasonnn** [comment]
暂时没有直接提供查询单个任务的接口, 可以通过先获取所有的记录然后过滤目标任务进行查询

**Comment by bossAnmi** [comment]
@ssseasonnn 1 任务太多（几十上百个）就会异常退出，是订阅不取消的问题吗。2 有下载，但获取不到所有记录 可能什么原因导致 的

**Comment by ssseasonnn** [comment]
把异常日志发出来, 自定义文件名请用Task

**Comment by ssseasonnn** [comment]
同一个url只会下载一次, 建议run一次demo,

**Comment by bossAnmi** [comment]
好的， 等异常重现我再贴上来，断网机制需要自己实现吧

**Comment by bossAnmi** [comment]
A/libc: Fatal signal 7 (SIGBUS), code 2, fault addr 0x79487cd000 in tid 20206 (RxCachedThreadS)
 *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
 Build fingerprint: 'HONOR/HDN-W09/HWHDN-H:7.0/HUAWEIHDN-W09/C233B072:user/release-keys'
 Revision: '0'
 ABI: 'arm64'
 pid: 19875, tid: 20206, name: RxCachedThreadS  >>> hence.com.tshow <<<
 signal 7 (SIGBUS), code 2 (BUS_ADRERR), fault addr 0x79487cd000
     x0   00000079487cd000  x1   0000000013d08010  x2   00000000000003be  x3   0000007975b95a10
     x4   0000000000000004  x5   00000000000003c2  x6   00000079487cd000  x7   20f533f30b39b2e6
     x8   113c5fa28736f99b  x9   000000006fc81f68  x10  0000000000000001  x11  0000000000000003
     x12  0000000800000000  x13  0000000070466238  x14  db333c81f20ce3d3  x15  0000000000000000
     x16  0000007975c227c8  x17  0000007978b15b08  x18  00000000ebad6082  x19  00000000000003c2
     x20  0000000000000000  x21  00000079487cd000  x22  0000007953dfd600  x23  0000000013d08000
     x24  0000007951cffe00  x25  00000079487cd000  x26  6569bd2f230c22bf  x27  0000007975b7644f
     x28  0000007975b7641e  x29  00000079518f3fb0  x30  000000797595bf34
     sp   00000079518f3ef0  pc   0000007978b15bb8  pstate 0000000000000000
 backtrace:
     #00 pc 000000000001abb8  /system/lib64/libc.so (memcpy+176)
     #01 pc 0000000000354f30  /system/lib64/libart.so (_ZN3art3JNI23GetPrimitiveArrayRegionIP11_jbyteArrayaNS_6mirror14PrimitiveArrayIaEEEEvP7_JNIEnvT_iiPT0_+792)
     #02 pc 0000000072492180  /data/dalvik-cache/arm64/system@framework@boot-core-libart.oat (offset 0x551000)

**Comment by bossAnmi** [comment]
@ssseasonnn 每次下载一定数量，就闪退，找不到其它异常日志

**Comment by ssseasonnn** [comment]
具体数量多少?

**Comment by ssseasonnn** [comment]
能否提供对应的下载url?

**Comment by bossAnmi** [comment]
一次性创建几百个manager，直接open too many异常。我是建立个类似队列，有时120多个，有时400多个闪退了
Fatal signal 7 (SIGBUS), code 2, fault addr 0x7949d4e000 in tid 27994 (RxCachedThreadS)

**Comment by ssseasonnn** [comment]
哥们...你是不是对手机性能要求太高了, 限制一下数量吧

**Comment by ssseasonnn** [comment]
新增了查询单个任务的API，没有其他问题先关闭了
