### ISSUE TITLE
同时开了5个任务跑，会出现崩溃的情况，两种方式都会出现（RxDownloadManagerKt.start和RxDownloadKt.download）

### ISSUE THREAD

**Issue by zhihuangcao** [ssseasonnn/RxDownload#289]
11-14 18:04:04.270 850-1218/zlc.season.rxdownload.kotlin_demo A/libc: Fatal signal 7 (SIGBUS), code 2, fault addr 0x7f5b423000 in tid 1218 (RxCachedThreadS)
11-14 18:04:04.330 23404-23404/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-14 18:04:04.330 23404-23404/? A/DEBUG: Build fingerprint: 'samsung/heroqltezc/heroqltechn:6.0.1/MMB29M/G9300ZCU2APL2:user/release-keys'
11-14 18:04:04.330 23404-23404/? A/DEBUG: Revision: '13'
11-14 18:04:04.330 23404-23404/? A/DEBUG: ABI: 'arm64'
11-14 18:04:04.330 23404-23404/? A/DEBUG: pid: 850, tid: 1218, name: RxCachedThreadS  >>> zlc.season.rxdownload.kotlin_demo <<<
11-14 18:04:04.330 23404-23404/? A/DEBUG: signal 7 (SIGBUS), code 2 (BUS_ADRERR), fault addr 0x7f5b423000
11-14 18:04:04.370 23404-23404/? A/DEBUG:     x0   0000007f5b423000  x1   000000003391e010  x2   0000000000001dd4  x3   0000000000000074
11-14 18:04:04.370 23404-23404/? A/DEBUG:     x4   000000006fb6b560  x5   0000000000002000  x6   0000000000002000  x7   0000007f5c7164f0
11-14 18:04:04.370 23404-23404/? A/DEBUG:     x8   00000000929c33be  x9   8082df943df12d23  x10  0000000000000001  x11  0000007f5b423000
11-14 18:04:04.370 23404-23404/? A/DEBUG:     x12  0000007f5c715858  x13  0000000000000000  x14  000000006fabf090  x15  0000007f7bc42888
11-14 18:04:04.370 23404-23404/? A/DEBUG:     x16  0000007f77ff9d90  x17  0000007f7bb81400  x18  0000007f77ffa000  x19  0000000000000001
11-14 18:04:04.370 23404-23404/? A/DEBUG:     x20  0000007f5cddba00  x21  0000007f77ffa000  x22  0000007f5d1b4600  x23  000000003391e00c
11-14 18:04:04.370 23404-23404/? A/DEBUG:     x24  000000006fb6b560  x25  0000000000000000  x26  0000007f5b423000  x27  000000003391e008
11-14 18:04:04.370 23404-23404/? A/DEBUG:     x28  000000003391e000  x29  0000007f5c7155e0  x30  0000007f77d09b40
11-14 18:04:04.370 23404-23404/? A/DEBUG:     sp   0000007f5c7155e0  pc   0000007f7bb81458  pstate 0000000000000000
11-14 18:04:04.380 23404-23404/? A/DEBUG: backtrace:
11-14 18:04:04.380 23404-23404/? A/DEBUG:     #00 pc 000000000001c458  /system/lib64/libc.so (memcpy+88)
11-14 18:04:04.380 23404-23404/? A/DEBUG:     #01 pc 0000000000340b3c  /system/lib64/libart.so (_ZN3art3JNI18GetByteArrayRegionEP7_JNIEnvP11_jbyteArrayiiPa+744)
11-14 18:04:04.380 23404-23404/? A/DEBUG:     #02 pc 0000000000159dc8  /system/lib64/libart.so (_ZN3art8CheckJNI23GetPrimitiveArrayRegionEPKcNS_9Primitive4TypeEP7_JNIEnvP7_jarrayiiPv+1080)
11-14 18:04:04.380 23404-23404/? A/DEBUG:     #03 pc 00000000000319f8  /system/lib64/libjavacore.so
11-14 18:04:04.380 23404-23404/? A/DEBUG:     #04 pc 000000000350fb5c  /system/framework/arm64/boot.oat (offset 0x2f5c000)
11-14 18:04:06.180 23404-23404/? A/DEBUG: Tombstone written to: /data/tombstones/tombstone_09
11-14 18:04:06.180 23404-23404/? E/DEBUG: AM write failed: Broken pipe
11-14 18:04:06.190 3334-3334/? E/audit: type=1701 msg=audit(1573725846.190:1124): auid=4294967295 uid=10306 gid=10306 ses=4294967295 subj=u:r:untrusted_app:s0:c512,c768 pid=1218 comm="RxCachedThreadS" exe="/system/bin/app_process64" sig=7
11-14 18:04:06.250 644-644/? E/lowmemorykiller: Error writing /proc/850/oom_score_adj; errno=22
11-14 18:04:06.270 1417-2115/? E/InputDispatcher: channel ~ Channel is unrecoverably broken and will be disposed!
11-14 18:04:20.550 1417-2475/? E/Watchdog: !@Sync 66312 [11-14 18:04:20.550]

**Comment by ssseasonnn** [comment]
这好像是内存不足导致的, 映射的内存被GC掉了, 可以减少同时下载的任务数量

**Comment by ssseasonnn** [comment]
fixed
