### ISSUE TITLE
启动下载后getalltask为空

### ISSUE THREAD

**Issue by shenzhenjinma** [ssseasonnn/RxDownload#290]
请问 RxDownloadKt.download() 下载文件后 ，
RxDownloadRecorder.INSTANCE.getAllTask().observeOn(AndroidSchedulers.mainThread()).subscribe()
拿到的列表为0，是什么情况呢

**Comment by ssseasonnn** [comment]
要用TaskManager的api下载才会保存下载记录, 你用Basic API 是不会有记录的

**Comment by shenzhenjinma** [comment]
RxDownloadManagerKt？

**Comment by ssseasonnn** [comment]
是的

shenzhenjinma <notifications@github.com> 于2019年11月26日周二 下午4:19写道：

**Comment by shenzhenjinma** [comment]
所以我要检查某个url是否下载，如果没有下载启动下载是这样吗？       
RxDownloadRecorder.INSTANCE.getTask(downUrl)
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new Consumer<TaskEntity>() {
                    @Override
                    public void accept(TaskEntity taskEntity) throws Exception { 
                        TaskManager tk= RxDownloadManagerKt.manager(taskEntity.getTask());
                        RxDownloadManagerKt.start(tk);


那么我通过这种方式启动如何监听这个url的下载状态呢？

**Comment by ssseasonnn** [comment]
首页文档有写怎么监听下载

**Comment by shenzhenjinma** [comment]
请问是这个吗
//keep this tag for dispose
val tag = taskManager.subscribe { status ->
    // Receive download status
    when (status) {
        is Normal -> {}
        is Started -> {}
        is Downloading -> {}
        is Paused -> {}
        is Completed -> {}
        is Failed -> {}
        is Deleted -> {}
    }
}

**Comment by shenzhenjinma** [comment]
ok
