### ISSUE TITLE
如何限制任务数

### ISSUE THREAD

**Issue by shenzhenjinma** [ssseasonnn/RxDownload#292]
你好，没有看到文档说明限制任务数，我简单看了下源码，请问是否使用
TaskManagerPool.INSTANCE.obtain
进行rxdownload4 的配置

**Comment by ssseasonnn** [comment]
1.0.9版本已经支持了

**Comment by shenzhenjinma** [comment]
如何使用呢

**Comment by shenzhenjinma** [comment]
class Task(
        var url: String,
        var taskName: String ,
        var saveName: String ,
        var savePath: String,
        var maxConCurrency: String
)
然后 
Task().download().observeOn(RxSchedulers.ui).subscribe()？
