### ISSUE TITLE
Information need

### ISSUE THREAD

**Issue by DeevD** [ssseasonnn/RxDownload#299]
let me know RxDownload 4 support custom extra data? i already use rxDownload 2 has custom extra data bro

**Comment by ssseasonnn** [comment]
No direct support, you need to rewrite your own Recorder

**Comment by DeevD** [comment]
Can you provide example for that?

**Comment by ssseasonnn** [comment]
Maybe I can support custom fields, wait a couple of days

**Comment by DeevD** [comment]
i think you need to support only one field bro  that make JSON string to save with custom multiple fields.

**Comment by ssseasonnn** [comment]
sounds good, thanks😁

**Comment by DeevD** [comment]
let me know when do you update for that?

**Comment by ssseasonnn** [comment]
Before today, I guess

**Comment by DeevD** [comment]
yyy thx bro

**Comment by ssseasonnn** [comment]
done

**Comment by DeevD** [comment]
ahh bro how can create a new task with extra info 
 i use these method 

`  val task = downloadUrl.createTaskManager()
    task.start()`
