### ISSUE TITLE
很不错啊，你那个下载的文件放在哪里

### ISSUE THREAD

**Issue by xwc520** [ssseasonnn/RxDownload#3]

**Comment by ssseasonnn** [comment]
默认在Download目录下

**Comment by liuzn0215** [comment]
发现一个小bug，在basic download中按完下载以后，在按了暂停以后，通过点击finish activity或者按返回键返回了以后，在打开此界面显示都是没有下载的，但是在按完下载后，是接着上一次下载的，等下载完的时候，看到的下载百分比是超过一百的，还有下载的大小是超过默认文件大小的，这个应该是一个小bug，希望楼主可以修复一下，挺不错的项目，支持一下

**Comment by ssseasonnn** [comment]
@liuzn0215 谢谢反馈, 尽快修复

**Comment by ssseasonnn** [comment]
@liuzn0215 你好, 你是在哪个分支上碰到下载进度超过100的, 我自己测试并没有发现这个问题
