### ISSUE TITLE
Multi-language support for Readme file

### ISSUE THREAD

**Issue by wotomas** [ssseasonnn/RxDownload#30]
Here is the PR! #29 

I think it should be a good start for the documentation to support multiple language!

**Comment by wotomas** [comment]
Feel free to leave any comments!

**Comment by ssseasonnn** [comment]
Thank you.

**Comment by ssseasonnn** [comment]
@wotomas Happy new year 😀

**Comment by wotomas** [comment]
@ssseasonnn No Problem! :D you too happy new year! I guess we can close this issue since the PR #29 is merged! 👍
