### ISSUE TITLE
中文文件路径，getFileNameFromUrl获取不了文件名

### ISSUE THREAD

**Issue by coder-pig** [ssseasonnn/RxDownload#307]
比如：

https://xxx.oss-cn-beijing.aliyuncs.com/2020-02-13/2020-02-13-23h/02_How's%20the%20weather_%E5%A4%A9%E6%B0%94%E6%AD%8C.mp3

**Comment by ssseasonnn** [comment]
可以手动设置task的文件名

**Comment by coder-pig** [comment]
设置了，是转义字符的原因...比如%20，直接替换为对应符号了~感谢

**Comment by BigBigDeBoy** [comment]
> 可以手动设置task的文件名

怎么设置文件名 和图标

**Comment by ssseasonnn** [comment]
请看Task类的定义
