### ISSUE TITLE
从安卓11开始 强制进行存储沙盒模式 希望可以自己填写保存文件路径

### ISSUE THREAD

**Issue by UsingMisz** [ssseasonnn/RxDownload#328]

**Comment by ssseasonnn** [comment]
创建task的时候不是可以穿savePath路径吗？

**Comment by UsingMisz** [comment]
安卓11从七牛云下载会出现问题

**Comment by UsingMisz** [comment]
![image](https://user-images.githubusercontent.com/18585336/105619929-6624de00-5e32-11eb-956f-9fecb8d87c3f.png)

**Comment by UsingMisz** [comment]
![image](https://user-images.githubusercontent.com/18585336/105619947-83f24300-5e32-11eb-9510-e154ac2f94c2.png)

**Comment by UsingMisz** [comment]
感谢大佬 穿savepath 问题已解决
