### ISSUE TITLE
关于使用Rxjava2与Rxjava1

### ISSUE THREAD

**Issue by liang1024** [ssseasonnn/RxDownload#33]
使用Retorfit+Rxjava结合时,只能使用Retorfit2+Rxjava1,使用Rxjava2会包冲突，希望作者能继续维护使用Rxjava1跟官方同步。

**Comment by ssseasonnn** [comment]
Retrofit可以和Rxjava2一起用啊，我项目中就是retrofit和rxjava2啊

**Comment by liang1024** [comment]
额，大神用的是Retrofit2嘛?我用retrofit2+Rxjava2,提示包冲突呢

**Comment by ssseasonnn** [comment]
你看我工程里gradle怎么写的

**Comment by liang1024** [comment]
好的.等有时间我clone下来瞅瞅~，谢谢啦

**Comment by CoderYanKang** [comment]
请问 compile 'zlc.season:rxdownload:1.2.8' 是否有这个版本的源码

**Comment by ssseasonnn** [comment]
github上的就是源码啊

**Comment by ssseasonnn** [comment]
可以看tag标记
