### ISSUE TITLE
Utils类的mkdirs函数里面是不是应该调用mkdirs呢

### ISSUE THREAD

**Issue by blackbbc** [ssseasonnn/RxDownload#34]
public static void mkdirs(String... paths) throws IOException {
        for (String each : paths) {
            File file = new File(each);
            if (file.exists() && file.isDirectory()) {
                log(DIR_EXISTS_HINT, each);
            } else {
                log(DIR_NOT_EXISTS_HINT, each);
                boolean flag = file.mkdir();   // 这里推荐使用mkdirs，防止父文件夹不存在的情况
                if (flag) {
                    log(DIR_CREATE_SUCCESS, each);
                } else {
                    log(DIR_CREATE_FAILED, each);
                    throw new IOException(format(getDefault(), DIR_CREATE_FAILED, each));
                }
            }
        }
    }

**Comment by ssseasonnn** [comment]
@blackbbc 好的，采纳了
