### ISSUE TITLE
Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.

### ISSUE THREAD

**Issue by Hardovsky** [ssseasonnn/RxDownload#343]
Hello!
Application crashes when the NotificationActionService try to create a pendingIntent on android 12.
We need something like this when we creating the pending intent:
` PendingIntent.FLAG_IMMUTABLE or PendingIntent.FLAG_UPDATE_CURRENT`

https://developer.android.com/guide/components/intents-filters#DeclareMutabilityPendingIntent

**Comment by ssseasonnn** [comment]
fixed

**Comment by Hardovsky** [comment]
awesome!
