### ISSUE TITLE
配置文件都是同一个URL，所以每次不管有没有更新都识别为同一个文件，有办法关闭这个缓存吗？

### ISSUE THREAD

**Issue by Marx-Hong** [ssseasonnn/RxDownload#350]
下载一个较大的配置文件，因为都是同一个URL，所以每次不管有没有更新，都识别为同一个文件，导致每次返回的都是第一次下载的缓存。这个缓存有办法可以关闭吗？

**Comment by Teemo100** [comment]
邮件已收到，三日内拜读

**Comment by ssseasonnn** [comment]
下载前先删除？

**Comment by Marx-Hong** [comment]
> 下载前先删除？

这是个办法，我是想问问看有没有API可以配置==
