### ISSUE TITLE
频繁点击清空缓存、下载出现崩溃，报错Fatal signal 7 (SIGBUS), code 2 (BUS_ADRERR)

### ISSUE THREAD

**Issue by shareware-open** [ssseasonnn/RxDownload#358]
使用最新版RxDownload，下载时清空应用缓存，再次点击下载，以此往复多次，出现崩溃，崩溃详情如下：
错误日志：
![截屏2023-04-20 10 39 05](https://user-images.githubusercontent.com/19420535/233245531-bb772076-b49f-444b-9d87-f3ba005c1faa.png)

错误代码指向：
![截屏2023-04-20 10 36 28](https://user-images.githubusercontent.com/19420535/233245579-808d77aa-68bd-4c47-9d06-461a8bbad02a.png)
麻烦大佬帮分析一下是什么原因呢

**Comment by Teemo100** [comment]
邮件已收到，三日内拜读

**Comment by shareware-open** [comment]
开了3个线程、分片大小8M，下载的文件为120M
