### ISSUE TITLE
我原项目中使用的是Rx1.0的库，然而你这个项目自带了RX2.0的库依赖冲突了有办法解决吗？

### ISSUE THREAD

**Issue by chenshaoyebj** [ssseasonnn/RxDownload#39]
我原项目中使用的是Rx1.0的库，然而你这个项目自带了RX2.0的库依赖冲突了有办法解决吗？是否可以灵活配置所使用的Rx库！

**Comment by ssseasonnn** [comment]
建议迁移至RxJava2，可以看更新日志的说明

**Comment by bean-liu** [comment]
一楼可以看看这个博客学习下Rx2.0，不过博主很久没更新了
http://www.jianshu.com/u/c50b715ccaeb
