### ISSUE TITLE
下载完成或安卓好退出后，下次调用 receiveDownloadStatus 时，收到的状态是正常，不应该是完成的状态吗？

### ISSUE THREAD

**Issue by ittianyu** [ssseasonnn/RxDownload#4]
做了一个类似于应用市场的demo，发现下载好的应用或已安装的应用，再次根据 url 去 receiveDownloadStatus ，第一次发射的状态是 NORMAL，建议根据应用是否安装，文件是否存在 发射 已安装，已完成。不然每次都要取下载记录。

**Comment by ittianyu** [comment]
另外建议加上 LeakCanary 检测内存泄漏。
我测试几次后发现一处内存泄漏：
后台下载 receiveDownloadStatus -> subscribe-> onNext  处发生泄漏。
个人猜测：onNext中要更新进度，所以保留了Activity 的引用，在Activity 退出后，引用依旧保留，导致了内存泄漏。
建议: 增加一个取消接收下载状态的方法，在onPause 中调用。

**Comment by ssseasonnn** [comment]
@ittianyu 你没有取消订阅，所以会内存泄漏，RxJava内置了Subscription可以取消订阅，文档中也有说明，请仔细看文档。

**Comment by ssseasonnn** [comment]
@ittianyu 关于状态的问题我后面测试一下，谢谢反馈

**Comment by ittianyu** [comment]
还有个问题，receiveDownloadStatus 这个方法调用后会一直监听吗？
我在得到下载地址后，调用了一次，然后点击按钮下载时，并没有下载进度的消息。
当我在点击下载后在调用一次该方法时，才能正常收到下载进度的消息。

**Comment by ssseasonnn** [comment]
是的，你可以下载demo查看用法

**Comment by ittianyu** [comment]
不好意思，是我写错了，两次传的url不一样。
但如果是已安装，返回的状态依旧是 已下载

**Comment by ittianyu** [comment]
如果已经下载，把文件手动删除后，返回的状态还是已下载。

**Comment by ssseasonnn** [comment]
安装这个字段现在并没有使用，因为并不只是会下载安装包文件。
文件删除这个问题下个版本修改。

**Comment by ssseasonnn** [comment]
@ittianyu 文件删除这个问题已经修复
