### ISSUE TITLE
servicedownload()方法下载过程中，下载进度跳动

### ISSUE THREAD

**Issue by gjjofsfe** [ssseasonnn/RxDownload#44]
servicedownload()方法下载过程中，下载进度跳动.
比如说:下载到67%突然跳到47%了，下载了一会儿后又跳到75%

**Comment by gjjofsfe** [comment]
今天使用了一下普通下载，也存在这个现象。

**Comment by caprice** [comment]
也有类似的问题，概率非常高。

**Comment by qinicy** [comment]
maxThread(n),n>=3大概率出现
