### ISSUE TITLE
希望加上自动检测是否重新下载，谢谢

### ISSUE THREAD

**Issue by gjjofsfe** [ssseasonnn/RxDownload#45]
启动下载到下载完成后，下次启动不知道是否下载成功，重试下载后重新开始下载了。
希望能自动检测如果下载成功过，就不在重新下载了。

**Comment by xieqiupeng** [comment]
暂时你可以performclick下载按钮，一旦检测到下载过，下载进度会变为百分之一百。

**Comment by ssseasonnn** [comment]
数据库里有记录啊，你查一下不就知道了，具体使用方式请看文档
