### ISSUE TITLE
能否判断是否有文件正在下载？

### ISSUE THREAD

**Issue by lizixian18** [ssseasonnn/RxDownload#46]
需求是在退出应用的时候判断是否要继续下载，所以能否判断是否有文件正在下载？应该加上判断数据库正在下载的记录是不是大于0就好了吧？

**Comment by xieqiupeng** [comment]
我觉得的你可以统计下载文件DownloadFlag的状态。

**Comment by lizixian18** [comment]
现在是这样判断
![image](https://cloud.githubusercontent.com/assets/16240767/23890940/fcedea24-08ce-11e7-9d27-2ee21f69f165.png)
