### ISSUE TITLE
有时下载完了不回调onsuccess

### ISSUE THREAD

**Issue by shaodong2528** [ssseasonnn/RxDownload#47]
我用下面这种代码在fragment中使用，有时下载完成了不回调onsuccess反而回调onerror这是什么原因啊

	RxPermissions.getInstance(mContext)
			.request(WRITE_EXTERNAL_STORAGE)
			.doOnNext(new Consumer<Boolean>() })
			.observeOn(Schedulers.io())
			.compose(rxDownload.<Boolean>transform(...)
			.observeOn(AndroidSchedulers.mainThread())
			.subscribe(new Observer<DownloadStatus>() {
		@Override
		public void onSubscribe(Disposable d) {
			//
		}
		@Override
		public void onNext(DownloadStatus status) { }
		
		@Override
		public void onError(Throwable e) { }
			
		@Override
		public void onComplete() { }
	});

**Comment by ssseasonnn** [comment]
那你把异常打印出来看看啊

**Comment by ssseasonnn** [comment]
那你把异常打印出来看看啊

**Comment by shaodong2528** [comment]
现在没有重现，但会出现下载失败的情况，当 下载失败后重试下载时就提示上下文为空，我是在listview的适配器里
Context is NULL! You should call [RxDownload.context(Context context)] first!

**Comment by ssseasonnn** [comment]
@shaodong2528 你不是用的最新版吧，现在Context是必传的参数。
