### ISSUE TITLE
连续点击下载暂停会下载出错！！

### ISSUE THREAD

**Issue by lizixian18** [ssseasonnn/RxDownload#49]
连续点击开始暂停开始暂停下载，会出现一下就下载完的bug，但是其实是没下载完的，下载下来的安装包大小虽然显示是正确的大小，但是是安装不了的，可以在demo里面试试。

我用的是这个链接，不支持断点的：
http://d.static.myappgame.com/qiu-fu-mo-lan-dan-dan-duo-dian-jiang-you-14571945118/qiu-fu-mo-lan-dan-dan-duo-dian-jiang-you-20170320.apk

**Comment by ssseasonnn** [comment]
你这个地址不支持断点续传。
不是一下就下载完了，是首先在本地创建了和将要下载的文件大小一致的文件，这个时候并没有下载完。

**Comment by lizixian18** [comment]
但是状态已经是变成COMPLETED 了，不应该啊

**Comment by caprice** [comment]
我想我的问题应该和楼上是一样的：
![image](https://cloud.githubusercontent.com/assets/2981114/25832056/cdb2c700-349a-11e7-81df-2ebad2ae9bcb.png)
如图中都显示COMPLETED状态，但其实下载目标文件的totalSize是不对的
