### ISSUE TITLE
打正式包时候 运行崩溃 是不是混淆的问题

### ISSUE THREAD

**Issue by BigBigDeBoy** [ssseasonnn/RxDownload#52]
ava.lang.IllegalArgumentException: Missing either @HEAD URL or @Url parameter.
    for method a.b
	retrofit2.ServiceMethod$Builder.methodError(ServiceMethod.java:720)
	retrofit2.ServiceMethod$Builder.methodError(ServiceMethod.java:711)
	retrofit2.ServiceMethod$Builder.build(ServiceMethod.java:206)
	retrofit2.Retrofit.loadServiceMethod(Retrofit.java:166)
	retrofit2.Retrofit$1.invoke(Retrofit.java:145)
	java.lang.reflect.Proxy.invoke(Proxy.java:397)
	$Proxy1.b(Unknown Source)
	zlc.season.rxdownload2.function.b.f(DownloadHelper.java:324)
	zlc.season.rxdownload2.function.b.e(DownloadHelper.java:318)
	zlc.season.rxdownload2.function.b.a(DownloadHelper.java:158)
	zlc.season.rxdownload2.function.DownloadService$b.run(DownloadService.java:1306)
	java.lang.Thread.run(Thread.java:818)

**Comment by ssseasonnn** [comment]
-dontnote retrofit2.Platform
-dontwarn retrofit2.Platform$Java8
-keepattributes Signature
-keepattributes Exceptions

混淆文件加上这个
