### ISSUE TITLE
多次调用下载方法，不抛异常，改为监听上次下载的状态

### ISSUE THREAD

**Issue by ImKarl** [ssseasonnn/RxDownload#53]
多次调用下载方法时，如果已存在该下载任务，则会直接抛异常。
=> 是否可以改为：已存在下载任务，则监听上次下载的状态。

比如这样的场景：

> 需要下载一个配置文件，可能在A位置或B位置 开始下载，AB位置需要同时显示下载状态。

如果所有类似场景都自己去判断，那代码必然变得很臃肿。

而且，如果在调用download() 之前没有去判断是否存在该任务，基本都是不太关心是否有存在相同任务的，只是希望把文件下载回来，调用download()后能监听到文件的下载情况。

**Comment by ssseasonnn** [comment]
receiveDownloadStatus这个方法在任何时刻调用均可接受到下载状态，不知道你有没有仔细看文档和demo

**Comment by ImKarl** [comment]
`如果所有类似场景都自己去判断，那代码必然变得很臃肿。`

我上面有解释，虽然可以实现功能，但判断逻辑需要每次调用download()前判断。或者只是让download()去触发下载，receiveDownloadStatus()才作为下载完成后的监听。

而且，目前对于`常规下载`（`Normal download`），并没有提供方法接收下载状态。

---

题外话：是否需要在框架内提供 `同一个url，保存到多个目标File` 的处理？

**Comment by ImKarl** [comment]
如果你觉得这些都不是问题，sorry，你可以直接关掉这个issues

**Comment by zhaoxiuyu** [comment]
@ssseasonnn  receiveDownloadStatus 这个方法回调 只会执行一次是吗？
