### ISSUE TITLE
下载卡顿

### ISSUE THREAD

**Issue by Drrino** [ssseasonnn/RxDownload#54]
点击下载  界面特别卡请问库当中有哪个方法可以解决

**Comment by 112721933** [comment]
这是因为receiveDownloadStatus的回调方法调用太频繁了，下载一个文件可能调用几千次，刷新界面过于频繁所以会卡顿，可以使用sample操作符限制调用次数。

`RxDownload.receiveDownloadStatus(url)
                .sample(200, TimeUnit.MILLISECONDS)  // 限制200毫秒调用一次
                .subscribe(new Consumer<DownloadEvent>() {
                    @Override
                    public void accept(@NonNull DownloadEvent downloadEvent) throws Exception {
                    }
                });`

**Comment by bappleug** [comment]
直接调用sample还是有问题的，因为各个下载状态都是从DownloadEvent里走的，sample的话基本上下载开始，下载暂停，下载结束等事件都被sample掉了。所以只能sample掉DownlodFlag=9992的event。

**Comment by bappleug** [comment]
例如如下采样：
`Observable<DownloadEvent> replayDownloadStatus = mRxDownload.receiveDownloadStatus(data.record.getUrl())
                .replay()
                .autoConnect();
        Observable<DownloadEvent> sampled = replayDownloadStatus
                .filter(new Predicate<DownloadEvent>() {
                    @Override
                    public boolean test(@NonNull DownloadEvent downloadEvent) throws Exception {
                        return downloadEvent.getFlag() == DownloadFlag.STARTED;
                    }
                })
                .throttleFirst(200, TimeUnit.MILLISECONDS);
        Observable<DownloadEvent> noProgress = replayDownloadStatus
                .filter(new Predicate<DownloadEvent>() {
                    @Override
                    public boolean test(@NonNull DownloadEvent downloadEvent) throws Exception {
                        return downloadEvent.getFlag() != DownloadFlag.STARTED;
                    }
                });`
