### ISSUE TITLE
这是什么原因啊,大神~Error:Connection refused

### ISSUE THREAD

**Issue by silentcmz** [ssseasonnn/RxDownload#56]
Error:Connection refused

**Comment by ssseasonnn** [comment]
挂代理，或者删掉build.gradle中bintray的依赖

**Comment by FrankKwok** [comment]
@ssseasonnn 遇到了相同的问题，删掉删掉build.gradle中bintray的依赖也不行

**Comment by ssseasonnn** [comment]
删掉gradle.properties里面的代理设置。
