### ISSUE TITLE
大神，求加上多任务上传的功能呢

### ISSUE THREAD

**Issue by wjbd** [ssseasonnn/RxDownload#6]
大神，求加上多任务上传的功能呢

**Comment by ssseasonnn** [comment]
你要哪种上传？要支持断点吗？

**Comment by wjbd** [comment]
恩，多线程多任务断点续传，能否集合到你的项目中去呢？两个合起来，我就不用多引入包了

**Comment by ssseasonnn** [comment]
上传比较难啊, 还要服务端配合, 不好做啊

**Comment by ssseasonnn** [comment]
你现在是用的什么上传?

**Comment by wjbd** [comment]
额，用的是Retrofit原生的。
像那种微信上传9张图片的那种多任务，多线程上传

**Comment by ssseasonnn** [comment]
@wjbd 我问一下, 你上传是上传到自己服务器还是上传到七牛或者阿里云这种地方?

**Comment by wjbd** [comment]
自己服务器啊，意思是要后台支持多线程上传？

**Comment by ssseasonnn** [comment]
不是, 你上传的时候不用增加别的请求参数?

**Comment by wjbd** [comment]
上传的时候要标记这个图片的唯一标识，就是这个用户的唯一标识

**Comment by ssseasonnn** [comment]
不用加token之类的?

**Comment by ssseasonnn** [comment]
那就是还得要额外的参数呀...我这边没法知道每个用户都需要哪些参数啊...

**Comment by wjbd** [comment]
token是肯定要的，所有的网络请求之前都加token，额外参数，好吧，那有没有一些推荐的文章啊？因为我了解的Retrofit上传图片，只了解了自带的方式。没试过其他的

**Comment by ssseasonnn** [comment]
这种只能你自己实现了, 对每张图片弄一个上传请求, 然后用Zip打包就行了, 其实也不难, 主要是每个用户用到的请求参数都不相同, 所以没法单独弄出来做一个库

**Comment by wjbd** [comment]
上传用zip打包，这是个什么概念啊？没了解过啊

**Comment by ssseasonnn** [comment]
上传请求不是这样定义的吗
Observable<Response> upload(...);
比如有多个上传请求:
Observable1, Observable2,Observable3. 
然后用Observable.zip(observable1,observable2,observable3,new Func()).subscribeOn(Schudules.io)...
这样就可以实现多线程上传啊...

**Comment by wjbd** [comment]
额~了解~我去百度一下，我用的是Retrofit，没结合Rxjava
