### ISSUE TITLE
receiveDownloadStatus调用次数过于频繁，导致界面卡顿问题

### ISSUE THREAD

**Issue by 112721933** [ssseasonnn/RxDownload#65]
使用receiveDownloadStatus监听下载进度的时候发现回调次数过于频繁，下载一个文件可能回调上万次，导致界面卡顿，可以使用sample操作符限制回调次数
`
RxDownload.receiveDownloadStatus("url")
                .sample(200, TimeUnit.MILLISECONDS)  // 限制200毫秒内只调用一次
                .subscribe(new Consumer<DownloadEvent>() {
                    @Override
                    public void accept(@NonNull DownloadEvent downloadEvent) throws Exception {
                    }
                });
`

**Comment by caprice** [comment]
确实我也遇到上面的问题，期待有更好的解决方案

**Comment by s13524801** [comment]
如果任务量很多，建议使用 getTotalDownloadRecord 监听下载

    private void updateDownloadStatus() {
        Disposable disposable = RxDownload.getInstance(this).getTotalDownloadRecords()
                .flatMap(new Function<List<DownloadRecord>, ObservableSource<DownloadRecord>>() {
                    @Override
                    public ObservableSource<DownloadRecord> apply(@NonNull List<DownloadRecord> downloadRecords) throws Exception {
                        List<DownloadRecord> list = new ArrayList<>();
                        for (DownloadRecord record : downloadRecords) {
                            if (record.getFlag() != DownloadFlag.COMPLETED) {
                                list.add(record);
                            }
                        }

                        return Observable.fromIterable(list);
                    }
                })
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new Consumer<DownloadRecord>() {
                    @Override
                    public void accept(@NonNull DownloadRecord downloadRecord) throws Exception {
                        // todo 根据 downloadRecord 匹配 position
                        if (commonAdapter != null) {
                            commonAdapter.notifyItemChanged(position);
                        }
                    }
                });

        compositeDisposable.add(disposable);
    }
