### ISSUE TITLE
同一样项目分了中英文版，在英文版上会出现下载百分比从0开始

### ISSUE THREAD

**Issue by shaodong2528** [ssseasonnn/RxDownload#66]
为什么有时候在下载时会突然下载到某一百分比时从新下载，而且有时间在下载时我如果暂停再下载也会出现从0开始，这个没有断点续传的效果了，我那个中文版的没有出现这个问题，这个英文版只是改了个语言而已，这是什么原因啊。

**Comment by bean-liu** [comment]
你测试下的文件是不是同一个？

**Comment by shaodong2528** [comment]
中英文地址是不一样，但后台说支持，这是其中一个地址：
http://videodownload.vrgameserver.com/videos/video/video-65ce58ee9b1849db8edf6480351533fb/video-65ce58ee9b1849db8edf6480351533fb.mp4

**Comment by bean-liu** [comment]
我用示例代码的ServiceDownload试了下你这个地址确实不能断点续传，暂停继续又从0重新开始，我又试着下载另外一个mp4文件，一样的不支持，然后我又找了个apk的下载地址试了下却没问题，继续下载是从暂停的断点位置开始，好奇怪🙁

**Comment by ssseasonnn** [comment]
@bean-liu @shaodong2528 断点续传是需要服务器支持的

**Comment by shaodong2528** [comment]
这个问题我考虑过，但把这个地址放在其它的下载框架或网上的一些demo中是可以实现断点继传的，我也觉得奇怪，这个地址是亚马逊的cdn的地址

**Comment by bean-liu** [comment]
Response{protocol=http/1.1, code=200, message=OK, url=http://videodownload.vrgameserver.com/videos/video/video-65ce58ee9b1849db8edf6480351533fb/video-65ce58ee9b1849db8edf6480351533fb.mp4}

Content-Type: video/mp4
Content-Length: 81632903
Connection: keep-alive
Server: Apache-Coyote/1.1
Accept-Ranges: bytes
ETag: W/"81632903-1493377111000"
Last-Modified: Fri, 28 Apr 2017 10:58:31 GMT
Date: Mon, 15 May 2017 03:08:16 GMT
Age: 30528
X-Cache: Hit from cloudfront
Via: 1.1 a7b52ef992771c7b94efcc5802d0589d.cloudfront.net (CloudFront)
X-Amz-Cf-Id: fam66yxeZ6Q6-YZ83ErF-h5UQrnwIwkDqGcqFDNSRI41w1intZeg8A==

---------------------------------------------------------------------------------------------------------------

Response{protocol=http/1.1, code=206, message=Partial Content, url=http://220.170.49.105/1/x/w/p/s/xwpsojvwrknbybkvoxfklnkvaeclrj/he.yinyuetai.com/B51A014EC514E7E7A14F2285DDF07E1D.flv?sc\u003d3f678269149a0c46\u0026br\u003d3156\u0026vid\u003d2238026\u0026aid\u003d45\u0026area\u003dHT\u0026vst\u003d0}

Server: T1_WEB/
Date: Wed, 17 May 2017 09:43:23 GMT
Content-Type: video/mp4
Content-Length: 101216093
Last-Modified: Sat, 25 Jul 2015 12:14:58 GMT
Connection: keep-alive
ETag: "55b37dc2-6086f5d"
Expires: Thu, 17 May 2018 09:43:23 GMT
Cache-Control: max-age=31536000
Content-Range: bytes 0-101216092/101216093

@shaodong2528 上面那段是你那个地址返回的响应头，下面是我另外找的一个视频的地址，你可以比较下，上面是不支持断点续传，下面这个支持断点续传。这个下载库是根据响应头里有没有Content-Range，Content-Length这两个标识来判断是不是支持断点续传，你的那个地址没有Content-Range所以就被判断为不支持咯，还有一点你那个响应码是200，按理来说支持断点续传的响应码应该是206。
