### ISSUE TITLE
在listview中的使用不是很理想

### ISSUE THREAD

**Issue by kyo2001lee** [ssseasonnn/RxDownload#69]
卡死问题在前辈的帮助下找到了解决办法，现在还有一个进度错乱的问题。。。。有遇到过的吗....

**Comment by lfcheong** [comment]
.....listview都是這樣的，與該插件無關，listview每次生成都要重新賦值，你百度一下就有了

**Comment by s13524801** [comment]
如果任务量很多，建议使用 getTotalDownloadRecord 监听下载

    private void updateCourseStatus() {
        Disposable disposable = RxDownload.getInstance(this).getTotalDownloadRecords()
                .flatMap(new Function<List<DownloadRecord>, ObservableSource<DownloadRecord>>() {
                    @Override
                    public ObservableSource<DownloadRecord> apply(@NonNull List<DownloadRecord> downloadRecords) throws Exception {
                        List<DownloadRecord> list = new ArrayList<>();
                        for (DownloadRecord record : downloadRecords) {
                            if (record.getFlag() != DownloadFlag.COMPLETED) {
                                list.add(record);
                            }
                        }

                        return Observable.fromIterable(list);
                    }
                })
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new Consumer<DownloadRecord>() {
                    @Override
                    public void accept(@NonNull DownloadRecord downloadRecord) throws Exception {
                        // todo 根据 downloadRecord 匹配 position
                        if (commonAdapter != null) {
                            commonAdapter.notifyItemChanged(position);
                        }
                    }
                });

        compositeDisposable.add(disposable);
    }

**Comment by ssseasonnn** [comment]
可以看下最新的版本，已经在代码中控制了界面更新的频率，不会导致界面卡死
