### ISSUE TITLE
下载速度减速

### ISSUE THREAD

**Issue by Cuieney** [ssseasonnn/RxDownload#70]
每次下载到百分之六七十左右就会出现下载速度降低很严重。之前的百分之五十下载速度会很快，demo里面的也存在相同问题 ，下载到七十左右会降速。

**Comment by bappleug** [comment]
确实，总有一个线程的速度很慢

**Comment by helei112g** [comment]
发现同样的问题，谁有解决方案？

**Comment by kkrr6840** [comment]
同样的问题，必然会出现有一个线程下载速度只有100k左右，其他线程是是3m每秒

**Comment by helei112g** [comment]
我使用的是  transferform形式。你们使用的是那种？

**Comment by bappleug** [comment]
已修复并提交PR，master分支应该已解决此问题。但好像没传到maven

**Comment by kkrr6840** [comment]
下载速度已经可以了，但是下载完成的文件都是损坏的，我在demo跟自己的应用都试了下。

**Comment by helei112g** [comment]
确实。出现同样的问题
