### ISSUE TITLE
暂定下载，再开始，文件会重新下载，而且本地文件会多一个出来

### ISSUE THREAD

**Issue by 494739635** [ssseasonnn/RxDownload#72]
多出来的文件名是  一串奇怪的字符

**Comment by 494739635** [comment]
![image](https://user-images.githubusercontent.com/12248420/26859446-556a8c88-4b6a-11e7-8dae-d8310df44730.png)

**Comment by 494739635** [comment]
@ssseasonnn 大神知道这个什么情况吗

**Comment by ssseasonnn** [comment]
这个可能是Content-Dispositon 解析错了， 你可以手动指定下载保存的文件名就可以解决这个问题。

494739635 <notifications@github.com>于2017年6月7日周三 上午10:16写道：
