### ISSUE TITLE
missionId 在数据库不存么

### ISSUE THREAD

**Issue by xiaomochn** [ssseasonnn/RxDownload#78]
![111](https://user-images.githubusercontent.com/8357946/27380001-188b0f6c-56b0-11e7-87df-c8f83ca74c7b.jpg)

82 行 是故意的么

**Comment by Wangct23** [comment]
图挂掉了

**Comment by xiaomochn** [comment]
zlc.season.rxdownload2.db.Db 这个类 下  
80行
如下代码是故意的 还是有问题 
if (empty(missionId)) {
values.put(COLUMN_MISSION_ID, missionId);
}
