### ISSUE TITLE
TemporaryRecord.getSaveName()空指针

### ISSUE THREAD

**Issue by bappleug** [ssseasonnn/RxDownload#84]
当多线程同时调用普通下载时，有几率发生次异常。问题原因应该在于TemporaryRecordTable中的TemporaryRecord是使用HashMap管理的，当多线程操作HashMap时出现了问题。
简单的解决办法是用ConrurrentHashMap替换HashMap

**Comment by bappleug** [comment]
这个地方还有问题。。同时多线程并发开始下载两个相同url，报出url already exists以后一个线程就把url从table删了，然后另一个线程拿url的时候报空指针。所以报already exists时是不能删除table中的相同url项的。

**Comment by Wanchen7** [comment]
我也遇到了。。。
