### ISSUE TITLE
监听进度问题

### ISSUE THREAD

**Issue by TruthKeeper** [ssseasonnn/RxDownload#89]
在2.0.4版本使用过程中，receiveDownloadStatus监听时，获取到的DownloadStatus对象中包含的下载进度以及已下载大小都不准，会突然变少，在RecyclerView中，并且网速较快的时候会有这个问题
![qq 20170718133451](https://user-images.githubusercontent.com/16833189/28302132-2520246a-6bbe-11e7-88d6-abad64203d9d.png)

**Comment by haganWu** [comment]
同样遇到了,有解吗?
