### ISSUE TITLE
数据库是自动存储的吗

### ISSUE THREAD

**Issue by a137235** [ssseasonnn/RxDownload#9]
那如果我下次需要得到已经下载和未完成的，是不是需要自己查询数据库呢？若sevice异常关闭，数据库会有问题不？

**Comment by ssseasonnn** [comment]
若你需要，我可以增加只获取已完成或者未完成的方法

**Comment by ssseasonnn** [comment]
不会有问题

**Comment by a137235** [comment]
有没有通知栏的实现呢？我想做个简单的实现：就是当下载队列里有任务时显示通知栏并显示数量，没有下载任务时隐藏。

**Comment by ssseasonnn** [comment]
没有，需要自己实现

**Comment by a137235** [comment]
能不能给点思路呢，需要修改你的库吗？

**Comment by ssseasonnn** [comment]
你添加一个下载任务就显示通知，下载完成更新通知数量就行了啊
